<?php

namespace Database\Seeders;

use App\Models\Medical;
use App\Models\RoleUser;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        //Admin
        $create_admin_user = new User();
        $create_admin_user->name = 'Admin';
        $create_admin_user->lastname = 'Sistema';
        $create_admin_user->email =  'admin@admin.com';
        $create_admin_user->password = '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi';
        $create_admin_user->save();

        DB::table('role_user')->insert([
            'user_id' => $create_admin_user->id,
            'role_id' => 2,
            'user_type' => 'App\Models\User',
        ]);

        //Medicos
        $names = [
            'Adriana Saucedo Reyes',
            'Carlos Etiene Cordero Jaime',
            'Elizabeth Joahana Ponce De León Leñero',
            'Ada García Monroy',
            'Julio Gaspar Trujillo Esteves',
            'Alberto Nájar Aparicio',
            'Francisco Alberto Wong Viccon',
            'Alicia Mandujano Mandujano',
            'Angel Octavio Bonfil Arias',
            'Arturo Montero Donatto',
            'Arturo García Correa',
            'Beatriz Adriana Pliego Meneses',
            'Beatríz Maldonado Tapia',
            'José Francisco Bulos Nicolás',
            'María del Socorro Ortíz Gea',
            'Jesús Ernesto Chong Vera',
            'Zenón Alejandro Ayala Berra',
            'Carlos Alejandro Ángulo Cruz',
            'Jesús Ángel Arroyo Moreno',
            'Armando Ashane Bulos',
            'Julián Ezequiel González Valdivia',
            'Héctor Hernández Cerritos',
            'Claudia Elvia Pérez Quesnel',
            'Arturo Cuatepotzo Durán',
            'Refugio Maldonado García',
            'Luz María Alonso Zenil',
            'Marcela Eugenia Bermúdez Morales',
            'Veronica Simancas Valencia',
            'Anel Hurtado Morales',
            'Erik Milton Tolentino Galván',
            'Heidy Juárez Fuentes',
            'Patricia Laurean Ibarra',
            'Manuel Ayala Almeida',
            'Leonardo Antonio Estrada Sosa',
            'Erika Corral Kassian',
            'Emilio Agustín Rodríguez Tavera',
            'Fernando Antonio Gómez López',
            'Facundo García Membrillo',
            'Kepler Garcia Leguizamo',
            'Juan Carlos Moreno López Ortega',
            'Haydee Solis Herrera',
            'Héctor Jaime González Cabello',
            'José Manuel Juárez Soto',
            'Ignacio Rodríguez Martinez',
            'José de Jesús Chávez Camacho',
            'Verónica Matías Hernández',
            'Alfredo Martín Laurrabaquio Miranda',
            'María Elena Ornelas Carsolio',
            'Miguel Vega Ortíz',
            'Luciano Ricardo Mendiola Figueroa',
            'Miguel Ángel Cruz Márquez',
            'Margarita Del Real Calzada',
            'María Altagracia Islas Salas',
            'María del Refugio Mejía Sánchez',
            'Javier Sánchez Nava',
            'Mario Jesús Antuña Alcázar',
            'Penélope Antonieta Noriega Zapata',
            'Luis Raúl Ramírez Piñon',
            'José Luis Castáñeda Narváez',
            'Silvia Elena Carrillo Nieto',
            'José Antonio Madrid Gómez Tagle',
            'Gabino Vera Vargas',
            'José Alberto Castillo',
            'Sony Amparo Loranca Corona',
            'Alejandra Priscila Juarez Ruiz',
            'Cynthia Karína Portillo González',
            'Rafael Agustín Mustieles Barragán',
            'Salvador Tejeda Tovar',
            'Sara Bertha Rodríguez Islas',
            'Ricardo Alberto Galván Arroyo',
            'Rodrigo Vásquez del Mercado Cordero',
            'Susana Nayeli Martinez Nava',
            'Luis Carlos Castillo Escutia',
            'José Luis Tejera Orozco',
            'Gerardo Ugarte De la Vega',
            'Humberto Vázquez Orihuela',
            'Yolanda Carrillo Arizmendi',
            'Gabriela Millotte Galíndo',
            'Carla Lorena Echevarría Céspedes',
            'Felipe Arteaga García',
            'Sugeily Valdelamar Mendoza',
            'Marcos Favela Mendoza',
            'Daniel Montaño Rios',
            'Adrian Palacios Cisneros',
            'Alejandro Moguel Hernández',
            'Jorge Arturo Ballesteros Barrera',
            'Abel Rodríguez Rodríguez',
            'Claudia Adriana Hurtado Ochoterena',
            'Marco Antonio Balanzario Poblano',
            'Francisco Ramirez Santa Rita',
            'Juana Marín Martínez',
            'José Carlos Anzures Aguilar',
            'Carlos De la Calleja Rodríguez',
            'Alberto Delgado Sandoval',
            'César Gíl Meríno',
            'Sergio Iván Assia Robles',
            'Diana Elizabeth Assia Zamora',
            'Eduardo González Barbosa',
            'José Felipe Pazos',
            'Fernando Marrufo González',
            'José Luis Concha de La Palacios',
            'José Luis Jorge Aguilar Herrera',
            'José Luis Madrigal Navarro',
            'Alejandro Alberto Terreros Moreyra',
            'Luz Irma Silvia Árias Ramírez',
            'José Francisco Espinosa Tenorio',
            'Rigoberto Santander Aldave',
            'Osvaldo Domínguez Andrade',
            'Alfredo González Castañeda',
            'Ana Patricia Martínez González',
            'David Servando Oropeza Rosas',
            'José Euberto Méndez Cisneros',
            'Jose Luis Santamaria Perez',
            'Alberto García Tepehuac',
            'Alfonso Zamora Ustaran',
            'Melitón Morales Castro',
            'Porfirio Antonio Valdivia Gallardo',
            'César Raúl Azcarraga De Lara',
            'Roberto Tepatzi Carranco',
            'Carlos Manuel González Rodríguez',
            'Juan Ricardo Ferrer Aldana',
            'Flavio Martinez Ortega',
            'Sandra Gabriela Salinas De la Chaussee',
            'Juana Bobadilla Ríos',
            'José Luis Sánchez Luna',
            'José Luis Velez Salas',
            'Juan Antonio Paleta Conde',
            'Ingmar Salvador Contreras Rivera',
            'Ignacio Manuel Tlapanco Barba',
            'José Leopoldo Galindo Cortés',
            'Marco Flavio Martínez Romero',
            'Josafat Roldán Áhuatl',
            'Josefina Sánchez Ramírez',
            'José Sergio Susano Pérez Tlapale',
            'Ricardo Marcelo Jimeno Arce',
            'Natasha Rosas Avila',
            'Ana Larissa Hernandez Garcia',
            'Arturo Zuñiga Barrios',
            'Isaac Jimenez Covarrubias',
            'Luis Javier Hernández Góngora',
            'Salvador Lima Jiménez',
            'Ramon Patiño Ramos',
            'Agustín Gutierrez Uriostegui',
            'Claudia Edith Montes Martinez',
            'José Rufino Guillermo Lima Sánchez',
            'Dora Imelda Cruz Cortes',
            'Nidia Grisell García Córdova',
            'Arisbeth Perez Becerra',
            'Alejandro Miguel Marín Ruíz',
            'Alejandro Pérez Lima Romero',
            'Luis Cipriano Bretón Hernández',
            'María Eugenia Rivera Domínguez',
            'Manuel Arturo Gonzalez Peña',
            'Gustavo Castáñeda Pérez',
            'Gregorio Mota Silva',
            'Hans Trujillo Moreno',
            'José Arturo Galíndo García',
            'Julián Rodríguez Orozco',
            'Judith González Carpio Larios',
            'Hector Mellado De la Cruz',
            'César Martín Flores Vera',
            'Alberto Jiménez Jiménez',
            'Rubén Delfino Villegas Sánchez',
            'René Mino Reyes',
            'Paz Irene Díaz Sosa',
            'Omar Ramírez Salazar',
            'Janet Álvarez Abreu',
            'Luis Coronel Cruzado',
            'Hugo Arturo Galindo Campos',
            'Dora Muñoz Huey',
            'Juan Manuel Calvo Gaytan',
            'Missael Arroyo Flores',
            'Leticia Rodríguez Villegas',
            'Omar Beltrán Galindo',
            'Beatriz Adame Avila',
            'Carlos Aknerth Salado Lima',
            'Carlos Asterio Salgado Krinis',
            'Gaspar Montesinos Ramírez',
            'Héctor Manuel Garza Rivera',
            'María del Carmen Enriqueta Melo Zurita',
            'René Gómez Ludwig',
            'Juan Manuel Figueroa Báez',
            'Eduardo Francisco Sumano Mora',
            'Martha Leticia Cruzalta Bahena',
            'José Luis Frías Rodríguez',
            'Raúl Segura Ponce',
            'Laura A. Pym Peña',
            'Juan José Delgado Donis',
            'Carlos Enrique Aguirre Tejedo',
            'Rocio Esmeralda Mateos Martinez',
            'Berenice Vergara Becerril',
            'Rogelio Silva Gutiérrez',
            'Blanca Graciela Robles Méndez',
            'Cecilia Carolina Hernández Dominguez',
            'César Alejandro Zúñiga Martínez',
            'Jesus Antonio Vazquez Avendaño',
            'Leonardo Santos Rodas',
            'Jesús Antonio Chandoqui Solís',
            'Adalberto Galdamez Barrios',
            'Jorge Marcey Villatoro Meza',
            'Francisco Javier Gallegos Aguilar',
            'Julio Andrés Salazar Farías',
            'José Benigno Moreno Ruíz',
            'Jesus Mario Altuzar Gordillo',
            'Israel Yberri Zarate',
            'Mario Alberto Cuesta Vázquez',
            'María de la Luz Sánchez Tirado',
            'Minerva Reyes García',
            'Jorge Arturo Pinto Astudillo',
            'Mario Alberto Ruíz Coutiño',
            'Mauricio Mijangos Lazos',
            'Yesenia Guadalupe Aguilar Penagos',
            'Pablo David De Coss Interiano',
            'Francisco Javier Medina Carranza',
            'Ricardo Montesinos Popomeya',
            'Alberto Pérez Pinto',
            'Rey David Estudillo Santiago',
            'Jesus Alejandro Moreno Salazar',
            'Alfonso Torres Aguilar',
            'Carlos Guillermo Najera Villatoro',
            'José Juan Corzo Ruiz',
            'Martha Karimy Merino Nazar',
            'Roberto Ochoa Muñoz',
            'Pablo Alberto Morales Lopez',
            'Miguel Sánchez Suárez',
            'Drina Rivas Bastidas',
            'Maria Jose Martinez Cristiani',
            'Pedro Mauricio Gomez Gutierrez',
            'Albino Velázquez Lagunes',
            'Russell Ricardo Valdéz González',
            'Elmer Gabriel López Chan',
            'William Martín Díaz Basto',
            'Roberto Greene Palacios',
            'Evelyn Azucena Cach Martinez',
            'Felipe Adrián Sánchez Losa',
            'Gabriel Valdéz Zapata',
            'Gabriela Raquel Vela Urtecho',
            'Gerlin Hernandez Peña',
            'Jorge Fabián Cruz Manzanero',
            'Nemias de Jesús Miam Quijano',
            'Kikey Coralia Achach Medina',
            'Luis Felipe Méndez Novelo',
            'Luis Augusto Manzanilla Félix',
            'Francisco Manuel Escalante Rejón',
            'Henry Nelson Perez Santiago',
            'Roger Eduardo Sánchez Avilés',
            'Vicente Martínez Gómez',
            'Fernando Trujillo Tobon',
            'Madai Esteves Cruz',
            'Alam Otoniel Medina Ventura',
            'Carlos Anastacio de Jesús Dib Fuentes',
            'Carlos Enrique Marrufo Y Olivares',
            'César Humberto Briceño Navarrete',
            'Irving Abelardo de Jesús Sauri Cruz',
            'Luis Manuel Bassó García',
            'Carlos Renán Lara Navarrete',
            'David Antonio Aguilar Castillo',
            'David Ernesto Cantó Chay',
            'Felipe José Díaz Rubio',
            'Armando José Briceño Pérez',
            'Carlos Manuel Quiñones Vega',
            'Francisco González Martínez',
            'Rossana Farías Cid',
            'Fernando Cardena Ángulo',
            'Hugo Hernán Cámara Combaluzier',
            'Héctor Herve Cabrera Baqueiro',
            'Ileana Guadalupe Alonzo Novelo',
            'Miguel Angel Gamboa Y Gamboa',
            'Martín Moo Marín',
            'Moisés Casares Montalvo',
            'Juan Pablo López Herrera',
            'Patricia Borjas Ale',
            'Teresa Magaña Garza',
            'Virginia Alicia Aranda Cázares',
            'Paul Ricardo Vivas Estrada',
            'Wilhelm Herve Cerón Grajales',
            'Zulmar Adiel Molina Ojeda',
            'Carlos Reyes Ordaz Ortiz',
            'Marco Antonio Escalante Rodríguez',
            'Alejandro Tercero Flores',
            'Cecilia Goreti Paredes Aquino',
            'Javier Ernesto Lara Canul',
            'Herbert Josué Puga Chan',
            'Alberto Jose Contreras Espinosa',
            'Daniel Armando Briceño Abraham',
            'Manuel Armando Parra Vinajera',
            'José Omar Peraza Llanes',
            'Jose Ariel Castillo Moguel',
            'Adolfo De Jesús García',
            'Alan Estrada Cardona',
            'Pedro Álvarez Vargas',
            'Beatríz Margarita Gutierrez Medina',
            'Juan Carlos Carrera Morales',
            'Eduardo Velázquez Carpio',
            'Fredy Cruz Mendoza',
            'Luis Arturo Ponce Rosas',
            'Bernardo Russek Portales',
            'Nancy Jiménez Paniagua',
            'Sergio Raúl González Adriano',
            'Elizabeth Solano Pareja',
            'Luis Miguel Alvarez Luna',
            'Erika Adriana Luna Gomez',
            'Carlos Jose Eysele Perez',
            'Gilberto Rosales Cervantes',
            'Mair Ivette Moreno Romero',
            'Héctor Francisco Marín Salvati',
            'Emmanuel Ramirez Sanchez',
            'Jaime Abraham Ceballos Flores',
            'María Katinka del Carmen Quintal Bastarrachea',
            'Luis López Gómez',
            'Marco Antonio Segovia Cuevas',
            'Javier Zapata May',
            'Gabriel Ruiz Villeda',
            'Juan Pedro Sánchez Campodonico',
            'Ernestina González Mercado',
            'Daniela Michell Aguirre González',
            'Araceli Monserrath Reyes Palomino',
            'Laura Fabiola Chávez García',
            'Roxana Noriega Alvarez',
            'Hania Beatriz Gasca Osorio',
            'Adolfo Feliciano Duarte Sánchez',
            'Cinthya Martínez Ruiz',
            'José Heriberto Álvarez Rojas',
            'Ángel Lara Valdés',
            'Alejandro Torres Castillo',
            'Oscar Alejandro Ruvalcaba Rojas',
            'Denisse Concepción Rodríguez López',
            'María Guadalupe Gómez Toledo',
            'Dulce María de Jesús Crespo Ruíz',
            'Andrés Hermida Moreno',
            'Erasmo Carlos Hernández Vega',
            'Ricardo Oliver Cano García',
            'José Alejandro Salmones Zarraluqui',
            'Manuel Vázquez Marcial',
            'Margarita Marina Ramírez Rivera',
            'Olga Patricia Vázquez Autrán',
            'Ruth Betsabé De Hoyos Robledo',
            'Rubén Eduardo Vázquez García',
            'Tobías Hamal Casab Tolosa',
            'Tomás Torres Manjarrez',
            'Dulce Alejandra Vargas Chávez',
            'Ana Magdalena Camarillo Duran',
            'María Alejandra Monzoy Ventre',
            'Anastasio Vicente Bautista González',
            'Bernardo Lira Rivera',
            'Sandra Charis Santiago',
            'Jaqueline Rosario Reyes Aguilar',
            'Claudia Díaz Sanguines',
            'Jessica Ortiz Moreno',
            'Yolanda Sánchez Ulloa',
            'Ernesto Lopez Lena Carrasco',
            'Gustavo Gomez Gomez',
            'Angel Jarquín Sandoval',
            'Héctor Tenorio Rodríguez',
            'Ittai Heidi Pérez Niño',
            'María Laura Javier Carreño',
            'Luis Alberto Sánchez Orozco',
            'Alberto Paz Pacheco',
            'Omar Santiago Hernández Lunagómez',
            'Fredy Roque Ruiz Hernandez',
            'José Ramírez Lázaro',
            'Carmen De la Cruz Sanchez',
            'Gabriela Hernandez Vez',
            'Adolfo Martinez Ibarra',
            'Gloria Cristina Ortiz Onofre',
            'Daisy Jimenez Cortes',
            'Luis Aquino Santiago',
            'Antonio Munguia González',
            'Carlos Alejandro Ortega Santos',
            'Alfredo Valentín Cruz',
            'Ruben Dario Meza Gutierrez',
            'David Huerta Morales',
            'Luis Fortino Díaz González Velázquez',
            'Ariana Bernal Zamora',
            'Arturo Roldan Arce',
            'Edgar Huerta Murrieta',
            'Gilberto Hernández Martínez',
            'Luis Antonio Díaz Vega',
            'Jorge Rubén Cañas Acar',
            'Jorge De Jesús Pascual Torres',
            'Maydelí Rosado Martínez',
            'Rafael Díaz Maraboto',
            'Gloria Elizabeth Verdejo Blanco',
            'Martha Patricia Hernández Ortega',
            'Brenda Cortés Zavaleta',
            'Zahira Talia Encina Barajas',
            'Maribel Morales Mezo',
            'Humberto Martínez García',
            'Carlos Elio Ríos Pérez',
            'César Augusto López García',
            'Darling Adriana Contreras Capetillo',
            'Eduardo Ramón Gorian Maldonado',
            'Efraín Ramón Aguileta Rodríguez',
            'Elisauro López Casanova',
            'Elias Cordova Sastre',
            'Armando Gómez Arredondo',
            'Gilberto Escobar Carrillo',
            'Gonzálo Antonio Neme Díaz',
            'Jose David Villalobos Horcasita',
            'José Luis Arias Arias',
            'José Luis Barrera Durán',
            'Jorge Antonio Gongora Canto',
            'Ignacio Vázquez León',
            'Juan Ramirez Loe',
            'Luis Antonio Requena Trejo',
            'Alfonso Alberto Rodríguez Olivera',
            'Maximiliano Gutiérrez Solís',
            'Ayda Milena Lázaro Lázaro',
            'Arturo Montalvo Marin',
            'Jesús Nuredim Del Ángel Assad',
            'Pedro Jiménez Ortíz',
            'William Lara Rada',
            'Raul Humberto Muro Flores',
            'Remigio Gómez Carrera',
            'Ricardo Nava Jacome',
            'Wendy Morales Salazar',
            'Iris Selene Quijano Mendez',
            'Amador Contreras López',
            'Alonso Cruz Hernández',
            'Francisco Gutiérrez Magaña',
            'Monserrat Gonzalez Flores',
            'Juan Javier Sobrino González',
            'Isaac Baltazar Gómez',
            'Bernardino Hernández Cortés',
            'José Román González Coron',
            'Alejandro Torres Bravo',
            'Romualdo Hernández Yañez',
            'Luis Juan de Dios Horta Sedas',
            'Mónica del Carmen Gómez Medina',
            'Patricia Guadalupe Hernández Toledo',
            'Martha González Vázquez',
            'José Antonio Sacre Hazouri',
            'Carlos Manuel Rodriguez Nocetti',
            'Carolina Ferreira Palma',
            'Jessica Neri Alvarez',
            'Augusto Rafael Aguilera Joaquin',
            'Gustavo Morales Espinosa',
            'José Ariel Cruz González',
            'Rosa Alba Gasca Ortega',
            'Gloria Mendoza Molina',
            'Amparo Chávez Gamboa',
            'Erick Daniel Limon Rodriguez',
            'Alfonso Maciel Torres',
            'Bonifacio Arturo Álvarez Figueroa',
            'Andrés Lagunes Viveros',
            'Fernando Castañón Leo',
            'Graciela Torres Martínez',
            'Blas Alcides Vargas Vargas',
            'Tomasa Gallegos Antonio',
            'Maximino Cerqueda Gallardo',
            'Pascual Vazquez Santos',
            'José Antonio Sánchez Carpinteyro',
            'Juan Carlos Galán Hernández',
            'Enrique Rodríguez Lara',
            'Jaime Peñarrieta Ruíz',
            'Yaradith Urueña Prado',
            'Mario Escalante De los Santos',
            'Mauricio Alberto Robles Vargas',
            'Sergio Valencia Soto',
            'Urbino Ripoll Hernández',
            'María de Lourdes Luján Beovide',
            'Ricardo Román Andrade',
            'Jorge Barbabosa Sosa',
            'Didier Vivas Fajardo',
            'María Lucila Chávez Soler',
            'Manuel Jesús Zavála Ávila',
            'Alejandro Palomino Sánchez',
            'María Teresa Mendoza Villegas',
            'Nancy Carolina Góngora Beltrán',
            'Kenia del Rosario Aguirre Gomez',
            'Carol Dalia Medina Duarte',
            'Manuel Castelán Fernández',
            'Evencio Hernández Burgos',
            'Lilia Arguijo Jimenez',
            'Karenn Rafaella Serrano Álvarez',
            'Virginia Abigail Velasco Juarez',
            'Jose Emilio Ramirez Perez',
            'Glenda Elizabeth Martínez Hernández',
            'Rubén Hernández Domínguez',
            'Juan Carlos Nicolás Álvarez Jonapa',
            'Eugenio José Ytuarte Nuñez',
            'Alfredo Muñoz Olivera',
            'Rosa Berenice Perla Posada',
            'Jose Edwin Villanueva Ojeda',
            'Luis Carlos Bates Méndez',
            'Paulina Trueba Villaseñor',
            'Pedro Luis Cruz Cu',
            'Alfonso de Jesús Díaz Noveló',
            'Denise Rosalba Guzman Lara',
            'Carlos Antonio Castillo Rosado',
            'José Antonio Aguilar Pérez',
            'Diego Armando López Rincón',
            'Jessica Guadalupe Jimenez Maza',
            'Berenice Angélica Flores Martínez',
            'Raul Limon Flores',
            'Liliana Marisol Santos Aguilar',
            'Víctor Serrano López',
            'Ana Cristina Ramirez Cortés',
            'Maria del Rosario Soto Hernández',
            'Gabriela López González',
            'Silvia America Paz Sandoval',
            'Marisol Márquez Leaño',
            'Carolina Samperio Perez',
            'Tiburcio Martin Romero Mira',
            'Miguel Ángel Mora Mejía',
            'Carlos Fernando Mosqueira Mondragón',
            'Carlos Enrique De la Paz Granja',
            'Jorge Luis Serrano Morales',
            'Carla Yásmín López Cortés',
            'Olga Lilia Cerda Pineda',
            'Eloisa Janet Barreto Toledano',
            'Eduardo Alonso Pliego',
            'Alfredo Yeudiel Martinez Vazquez',
            'Selene Sanchez Lopez',
            'Sandra Isabel Núñez Barrera',
            'Marilyn Julliet Romero Urbina',
            'Jazmin Gabriela Hernández Muñoz',
            'Belinda Leticia Arroyo Espinosa',
            'Rafael Elías Serrano',
            'Carlos Arturo Cantillo Maza',
            'José Luis Elizondo Aragón',
            'María Elizabeth Ayala Pérez',
            'Guillermo Enrique Muñoz Santiago',
            'Lina Luna Montes',
            'María Sara Nepomuceno De Lázaro',
            'María Elena Rico Escamilla',
            'Blanca Estela Téllez Jiménez',
            'Carlos Rivera García',
            'José Pánfilo Medina Alonso',
            'Yoan Fausto Perez Oliva',
            'Carlos Abel Morales Gonzales',
            'Iván Guerrero Ramírez',
            'Patricia Morales Salazar',
            'Gustavo Venegas Rosales',
            'Adriana Hernández Mejía',
            'Alejandra Ivette Muench Spitzer',
            'Alfonso Garay Espinosa',
            'Ana Karina Reyes García',
            'Víctor Manuel Sánchez Ortiz',
            'Diana Verónica Delgado Delgado',
            'Rosendo Enrique Vázquez Contreras',
            'Fedor Fernando López Villa',
            'Carlos Eduardo Góngora Cárdenas',
            'Marisol Dorantes Gómez',
            'Eduardo Armando León Tello',
            'Paulina Astatl Castellanos Aguilar',
            'Mónica Paola Mendoza Carlos',
            'Wendy Romero Lucas',
            'Martha Patricia Soto Ramos',
            'Sergio Arturo Echeverría Alarcón',
            'Mario Alfonso Sáinz Cázares',
            'Rodolfo López Garay',
            'Shugey Cabrera Corona',
            'Hugo Sergio González Rosales',
            'Alfonso Corona Téllez',
            'Francisco Antonio Mendizabal Bermúdez',
            'Jerónimo Colín Cano',
            'Daniel Constantino Martínez Millán',
            'Azucena Cortez Navarrete',
            'Edgar Salgado Carvajal',
            'Iván Rafael Aguirre Vázquez',
            'José Juan Rentería Morales',
            'Francisco Castro Torres',
            'Emiliano Galeana Arreola',
            'Freddy Santos Mariscal',
            'German Arquimides Garzón Barrientos',
            'José Antonio Camacho Nogueda',
            'Heriberto Flores Carmona',
            'Lucas Díaz Suárez',
            'Luis Ángel Ayala Romero',
            'Carlos Alberto Montero Uscanga',
            'María Del Carmen Contreras Alarcón',
            'Luis Antonio Jorge Zavala',
            'Sabino Vargas Espíritu',
            'Rafael Silva Barlandas',
            'Rafael Aguirre Añorve',
            'Respicio Montero Añorve',
            'Román Pineda Abarca',
            'José Luis Balanzar Serna',
            'Priscilla Sharaline Tejeda Ballhaus',
            'Jose Goben Arredondo Villanueva',
            'Ana Laura Luengas Sierra',
            'Moises Sanchez Diaz',
            'José Mauro Francisco Cabrera Andrade',
            'Magdaleno Agustín Cabrera Andrade',
            'Adrían González García',
            'Jesús Alejandro Grimaldi Carpio',
            'Alfonso Velasco Aznar',
            'Alfredo Aportela Abad',
            'José Alberto Cibrian Cruz',
            'Daniel Espinosa Zúñiga',
            'Heriberto Antonio Arista Viveros',
            'Eduardo Luna González',
            'Guadalupe Esperanza Ostos Ríos',
            'Gabriel Aguilar Piñón',
            'Raúl Gardida Chavarría',
            'María de la Luz Álvarez Rosas',
            'Jorge Ariel Maya Perez',
            'Jorge Luis Duránd Ortíz',
            'José Luis Pinacho Velázquez',
            'José Torrecilla Monzalvez',
            'Octavio Agustín Hernández Palomares',
            'Martha Patricia Sandoval Andrade',
            'Mario Carlos García Cruz',
            'Augusto Miguel Contreras Montaño',
            'Paris Sigifredo Córdoba Berman',
            'Verónica Bentata Medina',
            'María Guadalupe López Gómez',
            'Marcos Ricardo Vázquez Chavarría',
            'Rafael Juan Sánchez Galícia',
            'Gonzalo Manjarrez Hernandez',
            'Oscar Bernal Nava',
            'María Teresa Chavarría Jiménez',
            'Bertha Camacho Rogel',
            'José Luis Cruz Hernández',
            'Norma Lilia Romero Mejía',
            'Araceli Lara Muñoz',
            'Erick Francisco Estrada Rivas',
            'Martha Olivares Vázquez',
            'Manuel Aguilar Cancino',
            'Manuel Ángel Leyva Ramírez',
            'Jorge Valfre Alvarado Vargas',
            'Edgar Domínguez Arciniega',
            'Héctor Hernández Rivera',
            'Mariel Arana Segura',
            'Jose Emmanuel Leyva Nava',
            'María de los Gozos Cisneros Rivero',
            'José Manuel Cuevas Alvarado',
            'José David Flores Botello',
            'Javier Rodrigo Pantoja Espinoza',
            'Analia Palma Diaz',
            'Arely Gabriela Chavez Chavez',
            'Araceli Espinoza Castillo',
            'Carlos Manuel Lepe Olvera',
            'Ericka Quirino Jiménez',
            'Felipe Isaac Jiménez Pérez',
            'Yolanda Aguirre Hernández',
            'Héctor Manuel Fernández Madrid',
            'Mario Alejandro Orozco García',
            'Francisco Daniel Cetina Leon',
            'Alejandro Pimentel Domínguez',
            'Consuelo Guerrero Mengana',
            'Luis Alfredo Domínguez Sansores',
            'Jesús Amancio González Jaime',
            'César René Navarro Hernández',
            'Javier Ramírez Quiróz',
            'María del Carmen Paredes Martínez',
            'María Guadalupe López Nuñez',
            'Gilberto Morales Salgado',
            'Fernanda Aguilar Molina',
            'Ezer Cruz Rodriguez',
            'Miguel Ángel Cordero Miranda',
            'Xsiomara Moto Galván',
            'Martha Abad Acosta',
            'Patricia López González',
            'Martha Ivette Anchondo Martinez',
            'Edgar Alonso Monroy Zuñiga',
            'Arturo Saldívar Santini',
            'Carlos Antonio Quiroga Serrano',
            'Julián Javier Meza Verdugo',
            'Irene Lucila Lozano Cárdenas',
            'Manuel Alejandro Tovar Rivera',
            'Amanda Zoe Garcia Mendoza',
            'Juan Israel Cruz Jerónimo',
            'Carlos Villalobos Pérez',
            'Julio César Faz Garza',
            'Alan Enrique León Chaparro',
            'Gerardo Alonso Jimenez Flores',
            'Tomás Gómez Tamayo',
            'Daniela Reyes Ceceña',
            'Eulogio Muñoz Miranda',
            'Cristopher Efren Ruiz Vazquez',
            'Jetzabel Anaid Michel Robles',
            'Alejandro Alcantar Molina',
            'Estela del Sagrario Velázquez Gutiérrez',
            'Oscar Gerardo Cantu Rodriguez',
            'Daniela Patricia Castelo Toledo',
            'Ruben Rodriguez Armendariz',
            'Maricela Ávila Flores',
            'Abelardo Rojero Muñoz',
            'Andrés Abelino Fernández García',
            'Luis Bernardo Raigosa Serrano',
            'Antonio Contestabile Del Mistro',
            'Gustavo Acosta Escarzaga',
            'Laura Elena Acuña González',
            'Adria Belinda Berúmen Sánchez',
            'Adrián Pérez Ramírez',
            'Adriana Adelina Soto González',
            'Jorge Santiago Guevara Torres',
            'Marco Antonio Aguilar Martínez',
            'Aimeé Yazmín Ruiz Flores',
            'Alberto Casas Virgen',
            'José Alberto Esparza Luna',
            'Marco Antonio Alarcón Rivera',
            'Ramón Alberto Angulo Rosas',
            'Hector Alejandro Fernández Alcaraz',
            'Alejandro Ríos Aguirre',
            'Aleyda Zazueta Chávez',
            'José Manuel Alarid Ángeles',
            'Bertha Alicia Estrada Villa',
            'Alberto Alfonso De Luna González',
            'Alfredo Navar Saucedo',
            'Alma Rosa Sánchez De la Vega',
            'Alma Alejandra Heredia Guzmán',
            'Alma Lorena Montoya López',
            'Alma Elena Treviño Alvarado',
            'Alfonso Javier Marín Gómez',
            'Adán Almazán Mendoza',
            'Luis Lauro Lozano Montfort',
            'Angélica Iturburu Badillo',
            'Amelia Flores Quiróz',
            'Amarante Gutiérrez Martín',
            'Alberto Molina Colmenarez',
            'Angelina Contreras Herrera',
            'Ángel Medina Zenteno',
            'Luis Antonio Bojórquez Zazueta',
            'Jose Antonio Carrillo Cuevas',
            'Juan Antonio Mota Ortega',
            'Jose Antonio Arellanes Reyes',
            'Armando Ramos Flores',
            'María Graciela Arroyo Orozco',
            'Armin San Miguel Cadena',
            'Jesús Arturo Saldivar Martínez',
            'Rafael Aulis Campos',
            'Jesús Francisco Ayala Ramos',
            'Raúl Balleza Aranda',
            'Benito Israel Blancarte Montoya',
            'Alberto González Elizondo',
            'Emma Beatríz Exiga González',
            'Bernardo Fierro Hernández',
            'Carlos Ernesto Paredes Espinosa',
            'Brenda Janeth De Haro Hernández',
            'Bronson Osório Martínez',
            'Carmen Alicia Sánchez Ramírez',
            'Carlos Ramón Patiño Jiménez',
            'María de la Soledad Calvo González',
            'Sergio Camacho Larios',
            'Carlos Manuel Berrout Porras',
            'Carlos Puentes Ruiz',
            'Carlos Daniel Torres Luna',
            'Luis Carlos Luévano García',
            'Luis Carlos Porras Mendoza',
            'Emma Carolina Juarez Flores',
            'Carlos Alberto Siller Gutiérrez',
            'Carlos Emmanuel Chavez Sanchez',
            'Carlos Martín Corral Chávez',
            'Raymundo Estrada Gómez',
            'Cuauhtémoc Bojórquez Ascencio',
            'Carlos Humberto Salinas Salinas',
            'José Manuel Velasco Gutiérrez',
            'Manuel Ochoa Hernández',
            'Dora Alicia Carrera Reyna',
            'Elvia del Carmen León Olivares',
            'Rosario Figueroa Díaz',
            'Jorge Alberto Álvarez Pineda',
            'María Del Rosario Graciano',
            'Jorge Arturo Campos Garza',
            'Abelardo Ibarra Rodriguez',
            'Celeste María Botello Gámez',
            'Jorge Álvarez Lozoya',
            'César Ulises Víctor Barba Carrasco González',
            'Carlos Gabriel Cisneros Medina',
            'César Garza González',
            'Jaime Chávez Curiel',
            'Norma Cipatli Ayuzo Del Valle',
            'Brenda Cipres Cruces',
            'Christian Enrique Charles Paramo',
            'Jesús Terán Álvarez',
            'Jesús Manuel González Ortíz',
            'Dania Gonzalez Gonzalez',
            'Claudia Dolores Jiménez Robles',
            'Gonzálo Milán Gíl',
            'Rubén Olivares Jiménez',
            'Maico Velázquez Islas',
            'Pablo Bernardo Obregon Nava',
            'Erlinda Mabi Camacho Leyva',
            'Román González Rubio',
            'Rubén Soto Zavala',
            'David Alarid Coronel',
            'Alfonso Alvarez Hernandez',
            'Manuel Alberto Valencia Castellanos',
            'Alejandro Vicente Medrano Morlet',
            'Jesús Ernesto Brambila Benítez',
            'Ismaél Camacho Quintero',
            'María Concepción González Valdéz',
            'Carlos Gabriel Rivera Villaseñor',
            'César Alberto Lucio Ramírez',
            'Luis Fernando Espinoza Gonzalez',
            'Víctor Manuel Covarrubias Nuñez',
            'Francisco Javier Flores Gaxiola',
            'Francisco Valdés Rodríguez',
            'Francisco Antonio Méndez García',
            'Gabriel Martinez Gonzalez',
            'Jaime Gallardo Camargo',
            'Mario Luis Pineda Maldonado',
            'David Pinales Fuentes',
            'Sergio Javier Fernández Ortiz',
            'Rigel Gerardo Loera Gutierrez',
            'José Ignacio Cruz Rodríguez',
            'Dalia Guadalupe Olivares Bautista',
            'Luis Alfonso De Hoyos García',
            'David Eugenio Sanchez Ramirez',
            'Carlos Mario Méndez Nieto',
            'Marcela Romero Alcaraz',
            'Denisse Adriana De Osio Rojas',
            'Denisse Baez Lopez',
            'Dania Erika Quiñones Lopez',
            'Víctor Medina López',
            'Adán Zuñiga Salazar',
            'Abril Adriana Hernández Cisneros',
            'Adriana Cabrera Tijerina',
            'Gonzálo Torres Torres',
            'Guadalupe Gricelda Álvarez Swarez',
            'Delia Márquez Barreto',
            'Cecilia Del Carmen González Rosales',
            'Reynaldo Juan González Solís',
            'Miguel Contreras Flores',
            'Elsa Ivette Garza Hinojosa',
            'Marco Vinicio Cházaro Flores',
            'Rosa María Sánchez Santillán',
            'Juan Carlos Reyna Vázquez',
            'Argelia Hernández Mendoza',
            'Salvador Delgadillo Palacios',
            'Claudia Angélica Quezada Salazar',
            'Marisol Inzunza Balderas',
            'Ernestina Fernández Gómez',
            'Estela Abigail Zamudio González',
            'Adriana Elisa Aguirre Elizalde',
            'Claudia Guillermina Ramírez Olvera',
            'Claudia Angélica Rivera Posada',
            'Fabiola Edith Fernández Luna',
            'Elia Nohemi Hernández Camacho',
            'Martín González López',
            'Miguel Ángel Tarín Aranda',
            'Miguel Ángel Martínez Segovia',
            'María Lucía León González',
            'José Osbaldo Martínez Camacho',
            'Carmen Graciela Maraveles Álvarez',
            'Manuel Ochoa Tamez',
            'Agustín Odón Luna Gutiérrez',
            'Oscar Leonel Ibarra Soltero',
            'Dalila Martínez Tamez',
            'Carlos Alberto Torres Preza',
            'Enrique Guzmán Mejía',
            'Marbella Medina Osuna',
            'Leobardo Aldama Deciderio',
            'José Mendoza Graham',
            'Ángel Enrique Batista García',
            'María Elena Mora Echegaray',
            'Ramiro Requejo Alvarado',
            'Aníbal Padilla Kaim',
            'Jose Alfonso Vazquez Morales',
            'Norma Alicia Arreola Gómez',
            'Ricardo Eugenio Pérez Sánchez',
            'Ricardo García Tovar',
            'Magali Olave Moreno',
            'Ricardo Rojas Osuna',
            'Héctor Eduardo Arellano Romo',
            'Rosendo Gómez Galván',
            'Juan Carlos Rubí Carrizoza',
            'José Alfonso Sam Verdín',
            'Bertha Alicia González Solís',
            'Alejandro Santoyo Pérez',
            'José Ángel Serapio Martínez',
            'José Angel Topete Ponce',
            'Bernardo Adolfo Martínez Hinojosa',
            'Luis Manuel Valdés Nieblas',
            'Carlos Arturo Ramírez Rodríguez',
            'José Arturo Vela Staines',
            'Juan Carlos Cantú Elizondo',
            'Adolfo Verdugo López',
            'Víctor Martín Quezada Trasviña',
            'Carlos Alberto Martínez Vega',
            'Víctor Manuel Corona Gómez',
            'Marco Aurelio Castro Felix',
            'Florencio Ernesto Almaguer Cárdenas',
            'Eusebio Ángulo Castellanos',
            'Bruno Edgar Lopez Rivera',
            'Edgar Eusebio Aseff Córdova',
            'Daniel Casas Robles',
            'Edna Chugab Dermith Salazar',
            'Eduardo García Rodríguez',
            'Eduardo Llausas Magaña',
            'Eduardo Javier Velasco Sánchez',
            'Eldisa Guadalupe Fernández Duarte',
            'Emma Nayeli López Gaitán',
            'Jesús del Huerto David Domínguez Sosa',
            'Francisco Larios Arceo',
            'Gabriel Rodriguez Camelo',
            'Francisco Garza De León',
            'Juan Ricardo Garza Franco',
            'Gerardo Arturo Dávalos Cruz',
            'Gerardo Alarid Coronel',
            'Juan Antonio Caballero Ortiz',
            'Hugo Salvador Hernandez Nieto',
            'José Enrique Baltazar Guerrero',
            'Jesús Humberto Tapia González',
            'J. Jesús Ochoa Vargas',
            'Jaime Norberto Morales Muñoz',
            'Enrique Rodríguez Barragán',
            'Jesús Silva Romo',
            'José Ojeda Martínez',
            'Juan Jesús Peña Zamarrón',
            'Luis Alfredo Espinosa Cambero',
            'Manuel Aarón Escalante López',
            'Jorge Valdez Ceballos',
            'Esteban Mendoza Garza',
            'Eduardo Teneyuque González',
            'Justo Enrique Villeda Cuéllar',
            'Juan Jesús González López',
            'Leo Dan Isiordia Virgen',
            'Alejandro Limón Cota',
            'Juan Julio Jara Quispe',
            'Severiano Loera Bernal',
            'Javier López Morales Jr.',
            'Rafael Paredes Rodríguez',
            'Francisco Javier Escobar Navarro',
            'Manuel Alberto Flores Flores',
            'Fernando Javier Contreras Salazar',
            'Francisco Ornelas Cázares',
            'Francisco Gerardo Lozano Lee',
            'Heriberto Fuentes García',
            'Francisco Jose Carrillo De la Mora',
            'Gabriel Cortes Castañeda',
            'Gabriela Sereno Velázquez',
            'Gabriela Gurrola Lavalle',
            'Gabriela Hernández Orta',
            'Beatríz Inés Cruz Guajardo',
            'Guillermo Enrique García Quiróz',
            'Silvano Garate Ramírez',
            'Osvaldo García Salazar',
            'Jaime Castillo Ramos',
            'Genaro Garduza Zúñiga',
            'Gerardo Ramón Ramos Pantoja',
            'Gustavo Félix Beltrán',
            'Gerardo de Jesús Gutiérrez Vargas',
            'Gilberto Arrazola González',
            'Gerardo López Avilés',
            'María Virginia Gómez López',
            'Gordon Bennett Vidales',
            'Manuel Guajardo Jáquez',
            'José de Jesús Guerra Mendoza',
            'Gustavo Andrade Estrada',
            'Francisco Javier Saldaña Avendaño',
            'José Ángel Trujíllo Rendón',
            'Jazmin Viridiana Jimenez Carballo',
            'Francisco Javier Álvarez Rivas',
            'Javier Osorio Nava',
            'Juan Enrique Cruz Ortiz',
            'Jorge Luis Díaz Moreno',
            'Jesús Manuel Esquer Suárez',
            'Jesus Manuel Armenta Velderrain',
            'Jesús Cardona González',
            'Jorge Francisco Zorrilla Osuna',
            'Jesus Gutierrez Rojas',
            'Jesús Ernesto Valencia Córdova',
            'Laura Velasco Castro',
            'Alma Delia Guzmán Gallegos',
            'Humberto Lara Aguayo',
            'Juan Hernandez Flores',
            'Héctor Adrián García Hernández',
            'Héctor Ahumada Maldonado',
            'Héctor Cabrera Rojas',
            'Héctor José Paras Gómez',
            'Hugo Sergio Tamayo Vega',
            'Hugo Rolando Rentería Orozco',
            'Jorge Humberto Delgado García',
            'José Juan Alvarado Escobedo',
            'J Jesús Lázaro Gutiérrez',
            'Jose Luis Bustamante Olea',
            'José Luis Carbajal Paredes',
            'José Mario Turner Galán',
            'Juan Manuel Flores Doria',
            'José Francisco Vázquez Cuadras',
            'Jorge Castro Acedo',
            'José Luis Ibarra Rodríguez',
            'Jorge Adrián Chuck Sepulveda',
            'Jorge Fabián Santana Venegas',
            'Jorge Alberto Martínez Favela',
            'Jorge Pérez Lucio',
            'Jorge Antonio Rodríguez Mireles',
            'José Luis Gómez García',
            'José Ortíz Torres',
            'Javier Olivas Villagrán',
            'Jaime Gregorio Padilla Sencion',
            'José Gabriel Rosado Triay',
            'Juan Ramón Sauceda Avendaño',
            'Juan Manuel Ramírez Valdivia',
            'José Ramón Robles Elías',
            'Juan Manuel Gallaga Flores',
            'Juan Jose Serrano Figueroa',
            'Ignacio Argandoña Torres',
            'Mario Alfonso Inzunza Castro',
            'Ismaél David Piedra Noriega',
            'Ileana Reyes Guajardo',
            'Rosaura Peña Saldívar',
            'Sergio Iván Michel Correa',
            'Ivonne Delgado Herbert',
            'José Luis Tostado Márquez',
            'Julián Alfonso Cota Contreras',
            'Juan Manuel Ángel Sáenz',
            'Juan Miguel Ochoa Lopez',
            'Juan Rafael Buelna López',
            'Juana Juárez Madrigal',
            'José Lorenzo Villalobos Gutiérrez',
            'Jesús Vargas Zepeda',
            'Karene Marisol Perez Vargas',
            'Maria Enriqueta Lugo Heredia',
            'Juan Eduardo Velázquez Martínez',
            'Eduardo Rodriguez Gardea',
            'Zoila Lucia Lam Cobián',
            'Laura Elena Oseguera Martínez',
            'Doris Berrones Espericueta',
            'Jesús Alberto Leal Castro',
            'Gerardo Enrique Ledesma Chacón',
            'Luis Eduardo García Lafarga',
            'Lenin Francisco Castro Mendoza',
            'Luis Gerardo Flores Villanueva',
            'Luis Guillermo Ramírez Sánchez',
            'Lilia Fernandez Campaña',
            'Lilia García Escamilla',
            'Manuel Fabián Mora Valles',
            'Miguel Angel Franco Cervantes',
            'Lluvia del Carmen Hernandez Del Angel',
            'Micaela Rosales Ontiveros',
            'Lorenzo Morgan Avendaño',
            'Miguel Ángel Álvarez Carreón',
            'Lourdes Martina Almaguer Tamez',
            'Antonio Romero Saucedo',
            'Luis César Cantú Murillo',
            'Luis Carlos Arroyo Quintana',
            'Luis Rey Lopez Fragoso',
            'Miguel Ángel Bonal Pérez',
            'José Luis Macías Padilla',
            'María Magdalena Ramírez Méndez',
            'María Guadalupe Navarro Casados',
            'Martin Gerardo Salazar Salinas',
            'Enrique Manzanares Navarro',
            'Manuel Pérez Jiménez',
            'Manuel Garza Sánchez',
            'Marcelo Valdés Garza',
            'Marco Antonio Batres Medina',
            'Moisés Quiles Corona',
            'María de Jesús Montoya Rubio',
            'Martha Mónica Peña Garza',
            'Miguel Ángel Muñoz Pineda',
            'José Manuel Montesinos Cisneros',
            'Mario Alberto Saldaña López',
            'Mario Alberto Mendez Ortiz',
            'Mario Gutiérrez Castro',
            'Mario René Alcorta García',
            'Maria Eugenia Turner Larrinaga',
            'Marisela Esparza Rodríguez',
            'Adriana Ramirez Servin',
            'Marina Suárez Enríquez',
            'Claudia Mayela Aranda Saro',
            'Mariana Guadalupe Camargo Morales',
            'Mayela Carmona Sáenz',
            'Angel Mario Gomez Davila',
            'Mayra Yuridia Mune Maldonado',
            'Maricela Hernández Robles',
            'Luis Fernando Castillo Figueroa',
            'Jorge Villanueva Salinas',
            'Nelly Elizabeth Andrade Moreno',
            'Gerardo Arturo Nava Fuentes',
            'Jesus Alejandro Peña Gallegos',
            'Bernabé Darío Soto Gracia',
            'María del Rocío Moreno Galeana',
            'Nidia Haydee Ruvalcaba Padilla',
            'Juan Delfino Medina León',
            'Daniel Cardenas Fernandez',
            'Pavel Sosa Carrillo',
            'René Reséndiz Miranda',
            'Juan Bolívar Galeana',
            'Talia Conzuelo Gonzalez Fernandez',
            'Nozzett Cristina Ocegueda Chavez',
            'Enrique Gerardo Ortiz De la O',
            'Salvador Vázquez Ortíz',
            'Olga Lilia Rivas Hernandez',
            'Juan Ocampo Moreno',
            'Ana Elena Navarrete Ordoñez',
            'José Ernesto León Córdova',
            'Mitzi Monroy Molerez',
            'Karla Priscila Vázquez Padilla',
            'Ángel Vela González',
            'Javier Mario Torres Cadena',
            'Sergio Morales Conejo',
            'Omar Clemente Chavez Chaparro',
            'Jose Orlando Beltrán Chanes',
            'Jaime Orozco Pérez',
            'Ramón Reyes Lara',
            'Pedro González Hernández',
            'Estela María Robledo Conde',
            'Alma Patricia Salazar González',
            'Fernando Michel Penichet',
            'José Martín Silva Fonseca',
            'Luis Herrera Preciado',
            'Oscar Gerardo Herrera Aguilera',
            'Pedro Limón Rodríguez',
            'Jose Alfonso Quevedo Prieto',
            'Heriberto Pinto Aguilar',
            'Rosalba Herrera Bartolo',
            'Rosendo Valdéz De La Riva',
            'Rolando Antonio Salas Mercado',
            'Ruben Ruben Balderrama Davila',
            'Luis Felipe Aceves Navarro',
            'Salvador Pulido Díaz',
            'Antero Porras Mendoza',
            'Raúl Abundis Reyna',
            'Rafael Aguirre Romero',
            'Rogelio Andrade Ahumada',
            'Ramiro Vásquez Villalovos',
            'José Raúl García Martín',
            'Raúl Castañeda Bermúdez',
            'Teresa de Jesús Sánchez Gil',
            'Sandra Guadalupe Solís Gutiérrez',
            'Luis Alberto Contreras Zuñiga',
            'Severiano Leal Salinas',
            'Sidney Guillermo Guillot Verdugo',
            'Eduardo Antonio Reynosa Stenner',
            'Ricardo Javier Casas Mercado',
            'Adelelmo López Ricardi',
            'Ricardo Acosta Rodríguez',
            'Rigoberto Carrasco Felix',
            'Roberto Flores Santos',
            'Roberto René Reyes González',
            'Roberto Zazueta Tena',
            'Rodolfo Javier Venegas Mesina',
            'Roberto Hernández Raygoza',
            'Roberto Ruben Zuñiga Muñoz',
            'Silvestre Jesús Delgado Aguirre',
            'Rodrigo Alcides Aragón Mariscal',
            'Rodrígo Célis Pérez',
            'Silvia Dolores Pérez Córdoba',
            'Silvia Cano Enríquez',
            'Enrique Rodríguez Esquivel',
            'Sofía Elena Villarreal Valdés',
            'Alfonso Sosa Becerra',
            'Humberto Javier Soto Soto',
            'Gerardo Soto Abraham',
            'Santiago Antonio Sibrian Vega',
            'Juan Carlos Takasita Garza',
            'Sandra Leticia Cervantes De Hoyos',
            'Jesús Octavio Torres Jiménez',
            'Elia Thelma Pérez Rivera',
            'Ramón Tiberio Quezada Medrano',
            'María Teresa Medina Mendieta',
            'Jaime Julio Unda Gómez',
            'Víctor Manuel Cervantes Velázquez',
            'Héctor Vázquez Cavazos',
            'Víctor Eduardo Galván Arellano',
            'Teresa Elizabeth Vela Damken',
            'Ana Patricia Méndez Fuentes',
            'Marcelo Alejandro Valdés Gíl',
            'Víctor Hugo Portillo Araujo',
            'Porfirio Peña Ortega',
            'Luis Villalobos García',
            'Luis Fernando Villanueva Castro',
            'Víctor Manuel Piña Ceballos',
            'Victor Manuel Serna Langarica',
            'Xavier Alberto Gonzalez Gaona',
            'Luis Enrique Alatorre Montoya',
            'Wendy Medina Rodríguez',
            'Yeni Isabel Barboza Briones',
            'Yisell Ayma Zuñiga',
            'José Manuel Alanís Cajero',
            'Alejandro Guerra Tamez',
            'Zitlalic Hiramela García Salas',
            'Manuel Irak Ojeda Leon',
            'Julio Cesar Mosqueda Luján',
            'José Luis Nava Hernández',
            'Georgina Piña Ruíz',
            'Efraín Verdugo Verdugo',
            'Jose Rene Moreno Gomez',
            'Claudia Jazmin Ochoa Chavez',
            'Ana Laura Burgos Carvajal',
            'Lorena Castañeda Hernández',
            'Jesús Saúl Durán Nuño',
            'Ana Cristina Quirarte Solano',
            'Leobardo Mora Morán',
            'Victor Gerardo Sanchez Torres',
            'Marlene Susana Espinosa Rodriguez',
            'Jonathan Higgins Payán Díaz',
            'Emma Carolina Chaires Macías',
            'Ilsee De Leon Barragan',
            'Ignacia Villarreal Rodriguez',
            'Gabriela Inzunza Manjarrez',
            'Luz Isabel Zamudio Santos',
            'Fabiola Sanchez Michel',
            'Diana Rubi De la Rosa Gonzalez',
            'Martha Graciela Cardenas Sandoval',
            'Oscar Augusto Maldonado Vergara',
            'Anely Nájera Rubio',
            'Víctor Soto Torres Septien',
            'Omar Hernández Vargas',
            'Lorenzo Alejandro Cruz García',
            'Bibiana Marriaga Nuñez',
            'Susana Georgina Gallardo Robles',
            'Michelle Castro Cárdenas',
            'Jose Alfredo Gallegos Davila',
            'Margarito Jesús Ortíz Martínez',
            'Martha Berenice Posada De Leon',
            'Erika Guadalupe Leija López',
            'Pablo Isaac Saucedo Martinez',
            'Karina Margarita Cantu Sauceda',
            'Marisol Fernández Mercado',
            'Arturo Muller Méndez',
            'Roberto Humberto Galindo Ramírez',
            'Miguel Arturo Segura Delgadillo',
            'José René Aguilar Angulo',
            'Carmina Alejandra Zaragoza Mendez',
            'Paola Rabago Domingo',
            'José Martín Martínez Jaúregui',
            'Olga Leticia Ramírez López',
            'Jesús Pavel López Barrera',
            'Alfredo Porras García',
            'Aníbal Padilla Ochoa',
            'Cynthia Berenice Chavana Mijares',
            'Dennis Lorena Martínez Bejarano',
            'Diana Guadalupe Puente Sifuentes',
            'Alejandro Solís Kuri',
            'Jesús Servando Rivera Peña',
            'Jorge Eduardo Tapia López',
            'Luis Armando Barraza Nava',
            'Marisol De Los Reyes Cárdenas',
            'Héctor Alfredo Noyola Andazola',
            'Sofia Lopez de Arriaga Rojas',
            'Elizabeth Martinez Porras',
            'Héctor Daniel Yáñez Gordillo',
            'Eduardo Guadiana Villarreal',
            'Juan Carlos Félix Morales',
            'Fernando de Jesús Bodart Román',
            'Ana Rosa González Sánchez',
            'Argelia Dardane Laredo Flores',
            'Gabriel Gonzalez Sosa',
            'Saul Hernandez Perez',
            'Gabriela Cantú González',
            'Carlos José Jaramillo Casanova',
            'Lorena Maria Lerma Guerrero',
            'Jonathan Flores Ruiz',
            'Mara Alejandra Cazares Bellazetin',
            'Ana Margarita Martinez Roque',
            'Jesus Manuel Magaña Ley',
            'Tania Yazmín Moreno Rocha',
            'Tania Marcela Sifuentes Aguilar',
            'Christian Zamora Taravelsi',
            'Jesus Alan Chaparro Escudero',
            'Belda Erika Galicia Gonzalez',
            'Guillermo García Andrade',
            'Adad Yered Millán Hernández',
            'Liliana Meza Mondragón',
            'Aitana Voirol García',
            'Alejandro Alcántar Pérez',
            'Humberto Balderas Gaytán',
            'Carlos Vega Gómez',
            'Carlos Gustavo Murillo Cabrera',
            'Raquel Sagrero Reyes',
            'José Luis Miranda Esquivel',
            'Edgar Francisco Florián Martínez',
            'Oscar Misael Gutiérrez Medrano',
            'Javier Rosales Hueramo',
            'Jorge Alejandro Vázquez Narváez',
            'Juan Gabriel Franco Tinoco',
            'Jorge Enrique Estrada Carrillo',
            'Juan Pablo Martínez Hernández',
            'Liliana Verenice Arroyo Cruz',
            'Luis Felipe Murillo Núñez',
            'Luis Manuel González Gómez',
            'Luis Raúl Betancourt Morales',
            'Maria Eugenia Sánchez Gíl',
            'Alejandro González Ochoa',
            'Luis Manuel Anaya García',
            'Teresa Javier Martínez',
            'Eugenio Pacelli Chávez Contreras',
            'Enrique Arzate Mejía',
            'Pompeyo Pérez Marín',
            'Roberto Carlos Maya Vargas',
            'Víctor Manuel Urbina Rincón',
            'Raul De la Puente Murguia',
            'Edgar Adad Nieto Ruiz',
            'Mariana Jimena Diosdado Garcia',
            'Alfonso Mendoza Cendejas',
            'Liliana Elizabeth Martínez Reyna',
            'Jorge Luis Sánchez Victoria',
            'Miguel Ángel Aburto Chávez',
            'Teodoro Hernandez Estrada',
            'María Luisa Ochoa Ortiz',
            'Hilda Guadalupe Macias Ponce',
            'Edgardo Zúñiga Alvarez',
            'Guillermo Guerrero Rodríguez',
            'Melissa Mayela Burnes Quiroz',
            'Christopher Alan Ferretiz Rocha',
            'Fabián Huerta Ramos',
            'Leonardo Navarro Felix',
            'Yazmín Leyva Hernández',
            'Gicela del Carmen Tiscareño Ruvalcaba',
            'Bertha Alicia Mendoza Cárdenas',
            'Vicente Muñiz Juárez',
            'Francisco Antonio Pandeli Magaña',
            'Alfredo Cervantes Macías',
            'Ricardo Davila Vargas',
            'Rafael Eduardo Torres Lara',
            'José Joel Chávez Nevárez',
            'Carlos Garcia Perez',
            'Álvaro Aguilera González',
            'Luis Rolando Pineda Amezcua',
            'Ricardo Avalos Plata',
            'Marisol Cabanillas Ayon',
            'Saira Gaitán Martos',
            'Miguel Agustín Uranga Sánchez',
            'Sergio Cecilio Riestra Jiménez',
            'Alejandro Rojas Amaya',
            'Juan Pablo Gómez García',
            'Johanna Giselle Zúñiga Hernández',
            'Leticia Georgina García Campa',
            'José Armando González Cristopulos',
            'Enrique Octavio Félix Mendoza',
            'Jesús Efraín Sánchez Sandoval',
            'José Antonio González Chávez',
            'Juan Carlos Gutierrez Gonzalez',
            'Sandrino Jose Fuentes Alfaro',
            'Rubén Palestino Prudente',
            'Manuel Enrique De la O Cavazos',
            'Daniel Quintero Prado',
            'Salvador Romero Sánchez',
            'Carlos Ulises Araiza Martinez',
            'Hernan Cortez Tristan',
            'Alfredo Castorena Bustamante',
            'Edgard Grajeda Mata',
            'Rodolfo Boites Velarde',
            'Alma Rosa López Jiménez',
            'José Alejandro González González',
            'Adriana Bernarda Hernández Salas',
            'Esmeralda Ramírez Godínez',
            'Dulce Belén Cabrera Sandoval',
            'María Guadalupe Alejos León',
            'Juan Antonio Veytia Alvarez',
            'Francisco Javier Barrera Bravo',
            'Rodolfo Rincón Sánchez',
            'Carlos Adrián Mercado Morales',
            'Edna Elizabeth Meza Valle',
            'María del Carmen Sepulveda Orozco',
            'Daniela Perez Trujillo',
            'Salvador Flores Rubio',
            'Rey Jesus Hernandez Zuñiga',
            'Héctor Rolando Muzquiz Reyes',
            'Carlos Roel Sordo',
            'Christian Alejandro Lara Hernandez',
            'Efren Hugo Arroyo Orduño',
            'Raymundo Alan Castro Bravo',
            'Baruc Gómez Hernández',
            'Mario Adalberto Arredondo Briones',
            'Eduardo Isaac Rodriguez Rodriguez',
            'David Martínez Ruíz',
            'Arnulfo Macías Balleza',
            'Jesús Salvador Sánchez Santibáñez',
            'Amaranta Del Carmen Agraz Casillas',
            'Ana Maria Silva Guerrero',
            'Juan Eduardo Diaz Peña',
            'María Guadalupe López Martínez',
            'Francisco de Asis Ibarra Hernández',
            'Alexia Gisselle Vargas Rodriguez',
            'José Alberto León Sotelo',
            'Jesús Héctor Casanova Pérez',
            'Raymundo Sandoval Guerrero',
            'Aracely Acosta López',
            'Lucero Beatriz Campos Felix',
            'Rodolfo Antonio Espinoza Plana',
            'Silvia Valenzuela Taylor',
            'Ana Cecilia Chena Sánchez',
            'Eva Paulina Armas Quiroz',
            'Mayra Elizabeth Díaz Castillo',
            'Carmen Angelica Rentería López',
            'Aurora Elizabeth Santana Gómez',
            'Alejandra Ureña Ascencio',
            'María del Rocío Estrada Torres',
            'Juan Pablo Romo Gamboa',
            'Martha Adriana Sanchez Ramirez',
            'Arturo Emmanuel Sámano Caldelas',
            'Raúl Soria Villa',
            'Alejandra Espinosa Aguilera',
            'Juan Bosco Melo Pedraza',
            'Ilsi Murillo Rangel',
            'Jorge Herrera Gomez',
            'Rafael Eduardo Alcaraz Argumedo',
            'Francisco Vargas Saucedo',
            'Maria de Lourdes Carolina Miranda Flores',
            'Jorge Alberto Macias Flores',
            'Francisco Javier Salazar Grijalva',
            'Juan José González Miranda',
            'Miguel Angel Cuevas Vargas',
            'Gerson Madrigal Cedillo',
            'Jesus Aquilino Verdugo Bernal',
            'Leticia Sara Rosas Suárez',
            'Miguel Ángel Contreras Rodríguez',
            'Alberto Orozco Gutiérrez',
            'Jesús Ramírez Domínguez',
            'Juan Luis Cruz Juárez',
            'Beatriz Mendoza Ruelas',
            'Miguel Ángel Cantón Arenas',
            'Vicente Alfonso Huerta Pérez',
            'María Guadalupe Chávez Martínez',
            'Luz María Brena García',
            'Mayra Delgado Ayala',
            'María Del Rocío Porras Calderón',
            'Amador Armando Pereira Díaz',
            'Roberto Camargo Hernández',
            'Antonio Vega Valdés',
            'Reyna Alejandra Vargas Flores',
            'Enrique Ruiz Cardenas',
            'J Guadalupe Arturo Ambriz Maldonado',
            'Jazmín Verenice Jiménez Vázquez',
            'Juan Carlos Martinez Ruiz',
            'René Licea Claverie',
            'Jose Guadalupe Jaramillo Alvarado',
            'Ivette Huerta Niño de Rivera',
            'José Luis Serrano Gasca',
            'Miguel Angel Juarez Garcia',
            'Ana Paola Muñoz De la Cruz',
            'Antonio Calderon Moore',
            'Ismael Medina Orozco',
            'José de Jesús Gutiérrez Escobedo',
            'Narciso Bautista Olvera',
            'Claudia Fragoso Barrera',
            'Gabriel Alejandro Jaimes Brambila',
            'Blanca Estela Aguilar Gil',
            'José Luis Pasarin Montes',
            'Paloma Arenas Rojas',
            'Juan Carlos Rivera Rebolledo',
            'Efrain Velasco Luis',
            'Carina Gabriel Suarez',
            'Beatríz Cristina Herrera Castillo',
            'Juan Rodrigo Osegueda Mayen',
            'Rocío Lilián Esparza Anaya',
            'Alejandra Garcia Gonzalez',
            'Pedro Durán Hernández',
            'Teresita Parra Tello',
            'José Guadalupe Navarro Segura',
            'José Pruneda Dibildox',
            'Armando Colunga Dávila',
            'Mayra Idialia Alfaro Díaz de León',
            'Guillermo Ramón Franco Del Río',
            'Francísco Jesús Escalante Padrón',
            'Moisés González Gallardo',
            'Epifanio Angeles Molina',
            'Laura Cruz Navarro',
            'Elvia Verónica Cázares Moreno',
            'Benigno Trejo Montes',
            'Maria Soledad Galván Luna',
            'Alma Gloria Nieto Flores',
            'Ignacio Mancilla Morales',
            'Martha Paola Sánchez Soto',
            'Lucia Georgina Alcantara Parra',
            'Claudio Arturo Valencia Reyes',
            'Edgar López Díaz',
            'Yolanda Del Carmen Pérez Martínez',
            'Marcela Bernadett Gastelum Aguilar',
            'Jose Alfonso Laguna Contreras',
            'Claudia Elba Torres Malacara',
            'Gustavo Rodriguez Alcantara',
            'Erick Baltazar Palacios',
            'Francisco Javier Garcia Vargas',
            'Israel Villanueva Fernández',
            'Alberto Orozco Saucedo',
            'Antonio Vázquez Garduño',
            'Adriana Apodaca Dueñas',
            'Alejandro Berenguel Álvarez',
            'Abraham Huitxilihuitl Jauregui Luna',
            'Jacqueline Alejandra Gonzalez Landgrave',
            'Jonathan Morales Sanchez',
            'Antonio Elías Abraham Jalil',
            'Aaron Arturo Robles Ramirez',
            'Abigail Coutiño García',
            'Norma Ramírez León',
            'Nancy Tatengo Rodríguez',
            'David Zárate Meléndez',
            'Yazbeck Velazco Mendez',
            'Alfonso Copto García',
            'Alejandro Eduardo Alemán Valdés',
            'Rogelio Guillen Torres',
            'Héctor Gutiérrez Zuñiga',
            'Enrique Cobos Aguirre',
            'Alejandro Bautista Maldonado',
            'Arturo Fraustro Pérez',
            'Alfredo Aguilera López',
            'Gabriela Anastacia Colonia Albornoz',
            'Eduardo Pallares Coello',
            'Marco Antonio Cardiel Pérez',
            'Miguel Ángel Carreón Espejel',
            'Eduardo Alberto Naveda Alva',
            'Martha Patricia Gutiérrez Vilchis',
            'Luis Benito Sánchez Saavedra',
            'Mario Leonardo García Oliva',
            'Gregory Torres Palomino',
            'Aldo Eugenio Pestarino Meza',
            'Alejandro Jiménez Velázquez',
            'Alejandra Jiménez Guirola',
            'José Alejandro Hidalgo García',
            'Alicia Pérez Serafín',
            'Alfonso Eduardo Faure Vilchis',
            'Alejandro Rodriguez Rodriguez',
            'America Alanis Blancas',
            'Álvaro León Miranda',
            'Alma Yolanda García Betancourt',
            'Karla Sanchez Diaz',
            'Esperanza Herminia García Ortíz',
            'Luis Alpizar Soto',
            'José Emilio Juventino Cuautle Flores',
            'Jose David Michelle Perez Uribe',
            'Maria de los Ángeles Martínez López',
            'Francisco Gómez Medina',
            'Ana Débora Azuela Aldana',
            'Ángel Ballesteros Trujillo',
            'Fernando Augusto Ayala Urriola',
            'Norma Angélica Pedraza Pacheco',
            'Salvador Vaca Hernández',
            'José Gabriel Anguiano Delgado',
            'Carlos Enrique Angulo Benítez',
            'Viridiana Pantaleon Colin',
            'Jesús Manuel Ceceña Rodríguez',
            'Ivan Antonio Rivas Rivera',
            'Carlos Eduardo Hoyos Apodaca',
            'Alejandro Reyes Spíndola Ramírez',
            'Aureliano Zavála Mendoza',
            'Karla Fabiola Solís Solís',
            'Ines Alvarez De Iturbe',
            'Jorge Miguel Karam Jiménez',
            'Alejandra Sanchez Cruz',
            'Luis Miguel Cepeda Gutiérrez',
            'Jesus Humberto Oyarzabal Camacho',
            'Marisela Cuéllar Montalvo',
            'Ana Elena Limón Rojas',
            'Francisco Azahel Cortes Hernandez',
            'Bernardo Jardón Ugalde',
            'Belem Berenice Cruz Santiago',
            'Salvador Alfonso Calvillo Robles',
            'Lizeth Eugenia Carrizales Rodriguez',
            'Jesica Karen Martínez Saucedo',
            'César Antonio Noyola Salazar',
            'Blanca Lidya Torres Medina',
            'Beatriz Zuñiga Manriquez',
            'Brenda Bibiana Tenorio Rodríguez',
            'Sandra Lorena Bobadilla García',
            'Irene Brambila De la Cruz',
            'Marcela Mendoza Hernandez',
            'Daniel Martínez Sánchez',
            'Rafael Medrano Ocadiz',
            'Fernando Ríos Gutiérrez',
            'Braulio Isaac Palma Saldivar',
            'Julio César Del Valle González',
            'Alejandro García Jiménez',
            'Maria Guadalupe Esqueda Martínez',
            'Roberto Hernández Merino',
            'Alejandra Quiroga Valdés',
            'Joanna Alejandra Cardoso Biard',
            'José Guadalupe Cabrera Cabrera',
            'Ricardo Hugo Simroth Núñez',
            'Ana Teresa Chávez Ramírez',
            'Ramiro Alonso Aliaga',
            'Carlos Adon Gutiérrez Del Moral',
            'Carlos Espinoza Guerrero',
            'Carmen Brambila Basurto',
            'Carolina Méndez Zárate',
            'Enrique Prieto Hernández',
            'Roberto Castro Montoya',
            'José Manuel Unda Ugalde',
            'Daniel Eliseo Arzamendi Gutierrez',
            'Eduardo Flores Martin',
            'Maria Guadalupe Bautista Victoria',
            'José Miro Montaño',
            'Arnoldo Rafael Sierra Encinas',
            'Juan Ortiz Ocegueda',
            'Alberto Hernández Valle',
            'Raúl Bastida Medina',
            'Ildefonso Ugalde Olvera',
            'Ramsés Carlos Dorantes Piña',
            'Donaji Miranda González',
            'Dora Alicia Ramos Arce',
            'Dora Alicia Galindo Cavazos',
            'Eduardo Vargas Betancourt',
            'Edwing Reynaldo Ortiz Bernal',
            'Fernando Rodríguez Sixtos',
            'Ignacio Negrete Navarrete',
            'Víctor Manuel Mercado Ortiz',
            'Celerina Ortíz Ramos',
            'María del Rosario Ramírez López',
            'Cid Rafael Bravo Cortez',
            'Cinthya Bustamante Gallardo',
            'José Martín Lopez Amezquita',
            'Javier Saldaña Venegas',
            'Francisco González Valadez',
            'Elmer Jesús Muñoz González',
            'Maria Dolores Gutiérrez Serrano',
            'María Guadalupe Clara Vallejo Macías',
            'Luis Guillermo Meave Cueva',
            'Juan Martín Patlán Rodríguez',
            'Rubén Camacho Rivera',
            'Norma Elizabeth Castillo Macedo',
            'Fidel Shimasaki Nomura',
            'Rocco José González Morán',
            'Rodolfo Tinoco Diaz',
            'Mirna Edith Ramírez Menéses',
            'Jorge Luis Guerrero Martínez',
            'Eliseo Isaías Marín Salvatti',
            'José de Jesús Alcalá López',
            'María Esther Martínez Mercado',
            'Jorge Andrés González Nieto',
            'Gladis Tejada Martínez',
            'Maricela Guerrero González',
            'Emilio Enrique Gutiérrez Mendoza',
            'Jose Luis Zacarias Macias',
            'Anaith Guadalupe Valerio Limon',
            'José Luis Flores Estebanez',
            'Ana Maria Sanchez Ruelas',
            'José de Jesús Ríos Alba',
            'Alondra Sanchez Ruelas',
            'Agustin Francisco Cabrera Hermosillo',
            'María del Carmen Paredes Martínez',
            'José Luis García Chávez',
            'Carlos Humberto Gómez Guzmán',
            'José Luis Juárez Torres',
            'Jorge Rafael Ramírez Casillas',
            'Ernesto Ibarra Plascencia',
            'Luis Alonso Solórzano Escandón',
            'José Antonio López Lara',
            'Francisco Javier Orenday Martínez',
            'Miguel Angel Mata Flores',
            'Francisco Ricardo Pérez Diez',
            'Rogelio Ramos Velarde',
            'Ramiro Villanueva López',
            'Marco Antonio Carvajal Lopez',
            'Josué Isaac Estrada Almanza',
            'Cinthya Monserrat Sandoval Gonzalez',
            'Rene Rodrigo Lemus Samano',
            'Mario Santiago Antonio',
            'Sion Agami Micha',
            'Januario Estrella Jiménez',
            'Jaime Rodríguez Maldonado',
            'Evelyn Zoraida Cuandón Escobar',
            'Juan Angel De Leon Garza',
            'Delia Noemi Esquivel Callejas',
            'Juan Pablo Diaz Davalos',
            'Raymundo Lechuga Gutiérrez',
            'Arturo Perea Martínez',
            'María Isabel Díaz López',
            'Lucía Jaimes Hernández',
            'Jazmín Juárez Cabrera',
            'Jorge Aguirre Espinosa',
            'Dagoberto Alvarado Romero',
            'Virginia Irela Hernández Luna',
            'Érika Elizabeth Sánchez Schmitz',
            'Felipe Rey Rasgado Pineda',
            'Adán Ramírez Ocón',
            'Jose Emilio Benitez Sosa',
            'Jorge Ivan Chaparro Vazquez',
            'Nydia Arguelles Covarrubias',
            'María Angélica Ramos Álvarez',
            'Irma Patiño Gutiérrez',
            'Mónica Imelda Romo Peréz',
            'Blanca Xóchitl Salinas Reyes',
            'Angélica María Aguilar Ceniceros',
            'Verónica Caamal Jiménez',
            'María del Carmen Trinidad Pérez',
            'Claudia Olivares Nolasco',
            'Daniela Fernandez Pellon Fernandez',
            'Maria De Lourdes De Horta Martinez',
            'Elizabeth López Gachuz',
            'Gabriela Juarez Dominguez',
            'Adán Medrano Rojas',
            'Mirna Hernández Olguín',
            'Agueda Aguilar Pizaña',
            'Maria Juana León Reyes',
            'Martín Ramírez Soto',
            'Alejandro Pineda Flores',
            'Francisco Arturo Padilla Ramírez',
            'Raúl Puente Peña',
            'José Buenaventura Rojas Rebollo',
            'Raúl Héctor Roque Sánchez',
            'Rita Rodríguez Duarte',
            'Rosa Elena Andrade Baeza',
            'Rosa María Vázquez Cázares',
            'Arturo Salazar Acuña',
            'Roberto Serrano Rentería',
            'Gloria Silvia Aguilar Sánchez',
            'Silvia Ávila Zambrano',
            'Eduardo Suárez Del Real González',
            'Tomás Zepeda Muñóz',
            'Virginia Gaona Nava',
            'Dagoberto Terán Reyes',
            'Eduardo Alejandro Terreros Martínez',
            'Carlos Arturo Tirado Tirado',
            'Sergio Francisco González Aguilar',
            'María De Jesús Vergara Yoisura',
            'José Susano Ugalde Balcazar',
            'Carlos Hugo Medina Noyola',
            'Pablo Roberto Casaubón Garcín',
            'Victor Arturo Durán Corchado',
            'Jorge Antonio Castro Pineda',
            'Edgar Humberto Imaña Castro',
            'Eduardo Linares Juárez',
            'Efrén Rodríguez Lizárraga',
            'Efren Zaragoza Archundia',
            'Eduardo Zamora Dávila',
            'Elias Duck Hernandez',
            'José Eleazar Suárez Zárate',
            'Francisco Elmer Fontes Lohr',
            'Rolando Montes de Oca Navarro',
            'Elva Margarita Campos Figueroa',
            'Juana Elvia Castillo Calderón',
            'Ángel Montes de Oca Franco',
            'Jorge Octavio Olvera Sanchez',
            'Enrique Israel Amaya Juárez',
            'José Carlos Escandón Ojeda',
            'Francisco Javier Enríquez Rascón',
            'Eugenio Chávez Ramírez',
            'José Francisco Luna Sánchez',
            'Genaro Olvera López',
            'Jaime Vicente Jara Pérez',
            'Javier González Flores',
            'Hugo Valverde Franco',
            'J Jesús Enrique Torres Saldívar',
            'Juan Manuel Carbajal Macedo',
            'Jorge Alberto Perez Figueroa',
            'Esperanza Cuevas Legorreta',
            'Jorge Alberto Jiménez Lozano',
            'Víctor Jorge Flores Fonseca',
            'José Luis Cuadras Jiménez',
            'José Antonio Ríos Pérez',
            'José Luis González Esparza',
            'Gerardo Lara Aguilar',
            'Juan de Dios Varela Tenorio',
            'Eugenio Salgado Ruíz',
            'Erick Ramirez Ramirez',
            'Juan Francisco Álvarez Ibarra',
            'Luciano Mendoza Soto',
            'Manuel Antonio Song Trujíllo',
            'Luis Axel Estrada Guzman',
            'Marco Antonio Juárez Aguilera',
            'Mariano Rivera Echegoyen',
            'Miguel Ángel Alcázar Nieto',
            'Felipe de Jesús Oliveros Lozano',
            'Fernando Jiménez Millán',
            'Ricardo Urbina Arzate',
            'Francisco Javier Colín Navarro',
            'Fernando Pérez Porrúa',
            'Francisco Javier Díaz',
            'Luz Gabriela Varela Tenorio',
            'Rigoberto García Rivera',
            'Germán Navarro Vidaurri',
            'Jesús Gerardo González Adáme',
            'David González Flores',
            'Jorge Luis Girón Carrillo',
            'Gregorio Zenteno Macías',
            'Graciela Caballero Campos',
            'Adriana Guarneros Torres',
            'Gustavo Alonso Bustamante Monares',
            'José Antonio Uribe Moctezuma',
            'Edgar Jaziel Barroso Bermúdez',
            'Juan Javier González López',
            'Jacinto Jorge Martínez Ángeles',
            'José De Jesús Hernández Hernández',
            'José Guzmán Barcenas',
            'Gerardo Villarreal López Guerra',
            'Liliana Soto Garcia',
            'Héctor Ramón Guerrero Ortega',
            'Sofia Magdalena Juarez Barcenas',
            'Heriberto Vargas Bravo',
            'Rocío Hernández Villalobos',
            'José De Jesús Sanchez Sanchez',
            'José Luis Gerardo García Vela',
            'Jose Luis Gomez Lopez',
            'José Manuel Adolfo Tovilla Mercado',
            'José Mauricio Acero Garzón',
            'Juan Manuel Álvarez Marín',
            'Jorge Eduardo Granados Rosario',
            'Jorge Luis Hernández Arriaga',
            'José Luis Atzin Fuentes',
            'José Natividad Rodríguez García',
            'Jose Pablo Ura Hernandez',
            'José Pérez Cervantes',
            'José Luis Ramírez Haua',
            'Juan Ramón Torres Aguilar',
            'Luis Enrique Rosado Richard',
            'Jerónimo Sánchez Medina',
            'José Edilberto Suárez Nadal',
            'José Antonio Rocha Rivera',
            'Juan Carlos García Crespo',
            'Kenia Iraís Enríquez Fernández',
            'Irma Brassetti González',
            'Irma Regalado Contreras',
            'Israel Torres Coria',
            'Israel Castañon Torres',
            'María Isabel Delgado Arellano',
            'Itzzel López Alcantara',
            'Álvaro Manuel Ruíz Mendoza',
            'José Antonio Arizmendi Ramírez',
            'Adrian Nicolas Paredes Flores',
            'María Isabel Martínez Cruz',
            'Juana Ramírez López',
            'Juan Manuel García Higuera',
            'Juan Carlos Bautista Luna',
            'Julio Filiberto Chirinos Fano',
            'Rogelio Nolasco Jiménez',
            'Kenia Flores Montufar',
            'Juan Francisco Hernández Sierra',
            'Luis Landeros García',
            'Eulalia Rodríguez Cruz',
            'Jesús Luis Gerardo Cifuentes Romo',
            'Leonel Martínez Corona Duarte',
            'Alfredo Medrano Mata',
            'Leonidas Arteaga Botello',
            'Norma Leticia López Tamanaja',
            'Margarita Sánchez Miranda',
            'Cynthia Brenda Vega Juárez',
            'Verónica López Venegas',
            'Mario Eduardo Navarro González',
            'Daniel Flores Ramírez',
            'Juan José Guillermo Uríbe Ordóñez',
            'Miguel Hernández Paniagua',
            'Israel Cardenas Monteverde',
            'Lizandra Banderas Escobar',
            'Alberto Miguel Torres Toxqui',
            'Luis Monter Dipp',
            'Miguel Manuel Bernal Calzada',
            'Miguel Angel Serrano Mellado',
            'María Lourdes Hernández Suárez',
            'Miguel Enrique Blanco Del Toro',
            'Carlos Enrique López Lizano',
            'Jesus Manuel Lozano Garcia',
            'Lucía Carreto Molina',
            'Luis Mariano Ruíz Martínez',
            'Guadalupe Gómez Rodríguez',
            'María Gabriela Montes Ortíz',
            'Maria Magdalena Garces Perez',
            'Cynthia Dolores Pantaleon Colin',
            'Jesús Maldonado Rayas',
            'Martha Alicia Lledias Corona',
            'Luis Miguel Orozco Villalpando',
            'Rosa Carolina Castro González',
            'Heriberto Solano Larranaga',
            'Maria del Carmen Larios García',
            'Luis Monroy Aviles',
            'Monica Guadalupe Gonzalez Guajardo',
            'Carlos Javier Montoya Torres',
            'Maria de Lourdes Ramírez Balderas',
            'Margarito Marin Romero',
            'José Luis Mario García Nuñez',
            'Mario González Reyes',
            'Marina Perez Diaz',
            'Mario Renteria Centeno',
            'Marisol Sandoval Rodríguez',
            'Daniel Filiberto Martin Tamayo',
            'María Eugenia Sánchez O.Yudico',
            'Blanca Eugenia García Gámez',
            'Maximiliano Antonio Gutiérrez Gutiérrez',
            'Jonathan Alfredo Maya Epelstein',
            'Martín Ruedas Moreno',
            'Nancy Denise Garcia Maldonado',
            'Claudia Esther Quiriarte Cisneros',
            'Jorge Arturo Cardona Pérez',
            'Elia Noemí Camacho Ojeda',
            'Víctor Manuel Santiago Figueroa',
            'Luis Miguel Gomez Torres',
            'Omar Bravo Calderón',
            'Perla Leticia Ochoa Guajardo',
            'Orlando Jose Rodriguez Lopez',
            'Ignacio Alejandro Nájera Gutiérrez',
            'Beatriz Leonor Fernández Ruíz',
            'Gabriel Velez Walldez',
            'Germán Ramírez Alcocer',
            'Francisco Javier Morales Martínez',
            'Adriana Mancilla Moreno',
            'Carlos De la Vega Tejero',
            'Juan Martín Bermúdez Rodríguez',
            'Juan José Almaraz Navarro',
            'José Antonio García Martínez',
            'Francisco Martín López Ostendi',
            'Perla Yáñez Alvarado',
            'María Soledad Belmont Partida',
            'Rosa Lidia Trujillo Castillo',
            'Olga Lidia Romero Tejeda',
            'Rogelio Torres Guzman',
            'Rubén Alfaro Tapia',
            'Brenda del Carmen Sabanero Contreras',
            'Pedro Juan Cullen Benítez',
            'Apolinar Máximo Hernández Guerrero',
            'Leopoldo Antonio Talamantes Espinoza',
            'José Capuano Rafael',
            'Luis Enrique Cervantes Carmona',
            'Raúl Bahena García',
            'Lilia Ramírez Miranda',
            'Ramón García Zárate',
            'Guillermina Sánchez Moreno',
            'Juan Luis Saucedo Medina',
            'Sergio de Jesús Dávila Cameras',
            'Sergio Alejandro Lagunes Rodríguez',
            'Rubén Fermín Escobar Rodríguez',
            'Sergio Velasques Sánchez',
            'José Nicolás Reynes Manzur',
            'Ricardo Tomas Reyes Retana Valdes',
            'Jorge Octavio Ramírez Del Valle',
            'Rodrígo Aguilar Padilla',
            'Julio César Meléndez Carranza',
            'Óscar Solís Rodríguez',
            'Sotero Jesús García Reséndiz',
            'Sergio Troncoso Paredes',
            'Víctor Tapia Alfaro',
            'Santiago Unda Haro',
            'Gustavo Estolano Ojeda',
            'Griselda Alejandrina Tellez Laguna',
            'Sergio Gabriel Flores Salorio',
            'Odilón Romero Vázquez',
            'Miguel Trujíllo Ortega',
            'José Luis Gaitán Morán',
            'Alberto Uríbe Osório',
            'Valeriano Fuentes López',
            'María Patricia Vázquez Romero',
            'José Eduardo Valenzuela Olmeda',
            'Valeria Marquez Chin',
            'Verónica Cristina Alonso Juárez',
            'Martin Arturo Vargas Nieto',
            'Analizeth Carrillo Mendoza',
            'Víctor Payán Navarro',
            'Víctor Manuel King García',
            'Víctor Manuel Hernández Caballero',
            'Xochitl Josefina Pineda Rosas',
            'Irma Yañez Colín',
            'Carlos Razo Magallon',
            'Mariana Araceli Ortega Calderón',
            'Julia Isabel Hernández Luna',
            'Nayeli Moreno Nolasco',
            'Elizabeth Katherine Yorton',
            'Yolanda Aguilar Alvarez',
            'José Luis Caro Miranda',
            'Ana Karina Aguilera Lopez',
            'Patricia Méndez Paredes',
            'Juan Jose Perez Barragan',
            'Jose Antonio Alejandri Ramos',
            'Eva Cecilia Hernández Contreras',
            'Ana Dolores Ocegueda Estrada',
            'Yael Guadalupe Rocha Moreno',
            'Enrique Eduardo Milán Moreno',
            'Juan Carlos Tamayo Silva',
            'Jacqueline Brown Romero',
            'Esteban Gomez Morales',
            'Tizoc Gutiérrez Hernández',
            'Jesús Hernández Illescas',
            'Jose Andres Godoy Macias',
            'Raul Ruvalcaba Sufy',
            'Javier Chávez Tapia',
            'Rodolfo Muriel Vizcaino',
            'Ruth Yadira Luna Rojas',
            'Alfredo Fuentes Duarte',
            'Alfredo Perez Ordoñez',
            'Abril Alejandra Chuela Hernandez',
            'Mónica Estefanía De la Torre Pérez',
            'Alejandro Hernández Camberos',
            'Rodolfo Ismael Jimenez Martinez',
            'Raul Toledo Perez',
            'Ricardo Salinas Valiente',
            'Miguel Alejandro Longinos Vega',
            'Ismael Orozco Prado',
            'Barbara Leonor Ramírez Lara',
            'Walter Alan López Cadena',
            'Priscilla Lamshing Salinas',
            'Jose Tomas Rodriguez Martinez',
            'Xóchitl Santiago Reyes',
            'Griselda Guadalupe Vargas Robles',
            'Celeste Elisa Plowells Cavazos',
            'Mario Alberto Mata Vazquez',
            'Dulce Maria Aguilar Mata',
            'Oscar Amilcar Rubio Olvera',
            'Sergio Simerman Sanchez',
            'Miguel Ángel Robles Trejo',
            'Miguel Angel Mora López',
            'Mariela Barragan Quiñones',
            'Maribel Avila Mendoza',
            'César Alejandro Lopez Nava',
            'María Guadalupe del Socorro Lagunes Huerta',
            'Marina Beatríz López Rubio',
            'Saul Villa Bahena',
            'Raymundo López Cárdenas',
            'Magaly Ramírez González',
            'Karina Diaz Ramirez',
            'Martha Amparo Téllez Pérez',
            'Yuri Archivaldo Vargas Cuéllar',
            'Jorge Ramirez Martinez',
            'Maria Fernanda Calderon Maya',
            'Víctor Manuel Martínez Guzmán',
            'Inocencio Suárez Salazar',
            'Marco Antonio Mendoza Ojeda',
            'Julio Domingo Pacheco Amador',
            'Miguel Ángel González Cruz',
            'Carlos Alberto Gamez Villalobos',
            'Luz María Olivares Rodríguez',
            'Miguel Ángel Santos León',
            'Martha Alicia Pérez Gopar',
            'Alejandro Rojas Andrews',
            'Ana Cristina Azua Najera',
            'José Pablo Unda Haro',
            'Jose Rafael Lara Fraire',
            'Romel Dario Resendiz Ramírez',
            'Raul De La Cerda Navarro',
            'Gerardo Resendiz Cruz',
            'Maria Elizabeth Alvarez Rodriguez',
            'Miriam Chantale Vega Lopez',
            'José Ramírez Raya',
            'Elida Zavala Gómez',
            'Salvador Tirado Camarena',
            'Gloria Pila Aranda',
            'Oscar Trujillo Nava',
            'Arturo Partido Ramírez',
            'Natalia Lizola Arvizu',
            'Raul Delgado Valdez',
            'Nancy Anai Pérez Rincón',
            'Esau Waldo Montoya Jiménez',
            'Juan Humberto Gutiérrez Alanís',
            'Marlen Erika Montes Cardenas',
            'Arandi Ávila Reséndiz',
            'Martha Hilda Rubio Cacique',
            'Mario Héctor Blancas Ojeda',
            'Clarinda Alejandra Garibay Zavala',
            'Blanca Tinoco Sámano',
            'Raquel Márquez Zermeño',
            'Yamilet Hernández Avendaño',
            'Samaria Cruz Santiago',
            'Rafael Hernández Aragón',
            'Mauricio Lopez Acevedo',
            'Laura Isabel Panduro Valdez',
            'Maricela Galicia Hernandez',
            'Andrea Lizbeth Corona Cordero',
            'Mirna Alicia Salas Samaniego',
            'Gabriela Pereda Torres',
            'Yunuen Ramirez Narvaez',
            'Karla Lourdes Nava Tirado',
            'Luis Alfredo Domínguez Sotelo',
            'Yine Hernández Márquez',
            'Marco Antonio Galvez Roldan',
            'Lidia Edith Diaz Romero',
            'Diana Yaneli Aquino Villagómez',
            'Gibrán Peña Bonales',
            'Carlos Alberto Velasco Alonso',
            'Ramiro Soto Soto',
            'Steephany Guzman Luna',
            'Daniel Vargas Becerril',
            'Arianna Guerrero Campa',
            'Gabriela Paloma Morlan Lopez',
            'Richard Anaya Ornelas',
            'Ricardo Ugalde Carreón',
            'Jorge Jesús Salinas González',
            'Perla Hernandez Licea',
            'Rebeca Elisa Guerrero Patiño',
            'Nicolás Paredes Melesio',
            'Yair Hernández Santiago',
            'María Elena Rivera Reynoso',
            'Luis Manuel Suárez Flores',
            'Lino Eduardo Cardiel Marmolejo',
            'José Antonio Chávez Barrera',
            'Irma Garrido Lecona',
            'Jorge de Jesús Field Cortazares',
            'José Isaac Valenciano Vega',
            'Eugenia Hernández Suárez',
            'Gabriela Ramírez García',
            'Fernando de Jesús Lavalley Echeverría',
            'Nadia Gisela Ramirez Vargas',
            'Ignacio Alberto Portales Pérez',
            'Edith Lechuga Ávila',
            'Delia Figueroa Pineda',
            'Martha González Tepozan',
            'Eduardo Almanza Madariaga',
            'María Auxilio Torres Silva',
            'Rodolfo Ruiz Garcia',
            'Emmanuel Torres Arnaut',
            'Maria Mercedes Mercado Meza',
            'Darío Ángeles Rodríguez',
            'Hugo Villa Ramírez',
            'María Angélica García Burciaga',
            'Brenda Abigail Reyes Huerta',
            'Jose Enrique Mancilla Anguiano',
            'Raúl Linares Osoyo',
            'Noe Belmar Díaz Gómez',
            'Mayra Patricia Arteaga Mancera',
            'Adrián Ceballos Bocanegra',
            'Arianna Parra Ibarraran',
            'Marco Antonio Urbina Ayala',
            'María del Pilar Reveles García',
            'Mariana Canseco Herrera',
            'Jesús Bernardo González Castellanos',
            'Selene Marcelo Orozco',
            'Patricia Díaz López',
            'Jose Antonio Rojas Gomez',
            'Samuel Guzmán Tobías',
            'Ana Laura Moguel Mendez',
            'Arturo Espíndola Díaz',
            'Alejandra Rojas Ramos',
            'Ander Emmanuel Octavio Dubon Suarez',
            'Rafael Zepeda Ramos',
            'José Luis Morelos Poxtan',
            'Maurilio de Jesus Romero Hernandez',
            'Edson Eduardo Cruz Gonzalez',
            'Nelly Guadalupe Morales Molina',
            'Julio Cesar Pineda Hernández',
            'José Arenas Benhumea',
            'Anarely Peralta Olivares',
            'Ciro Hernández Bernabé',
            'Israel Rincón Zarate',
            'Victor Manuel Sanchez Molina',
            'Francisco Alfonso Solis Espinoza',
            'Mario Aguilar Gutierrez',
            'Nicolás Árias García',
            'Francisco Gutiérrez Castillo',
            'Noe Ortiz Cruz',
            'Carlos López Candiani',
            'Claudia Montesinos Ramírez',
            'Eva Julieta Hernández Archundia',
            'Rafael Domínguez Aguilar',
            'Ines Georgina Lopez Pineda',
            'Arturo de Jesus Buenfil Herrera',
            'Armando Cuauhtémoc Garduño Ruíz',
            'María del Rayo Crispín Rodríguez',
            'Julian Saenz Garcia',
            'José Mario García Martínez',
            'Miguel Angel Karlis Rangel',
            'Jorge Alberto Torres Bernal',
            'Kathia Castelán Muñoz',
            'Leticia Valenzuela García',
            'Mara Areli Guajardo Gonzalez',
            'Miguel Ángel Maldonado Fuerte',
            'Oswaldo Juangorena Lopez',
            'Sergio Guadalupe Jacobo Díaz',
            'Aleyda Monreal Malacara',
            'Fidel Castañeda Contreras',
            'Irene María Garcia Olivo',
            'Dulce Paola Navarrete Garcia',
            'Ben David Valdés Ramos',
            'Lucía Leonor Cuevas López',
            'Sandra Patricia Lagunes Salazar',
            'Ary Pérez Jaramillo',
            'Eltzy Rubí Rocha Rivera',
            'Jorge Arturo Chávez Saénz',
            'Olivia Blancas Jacobo',
            'Oscar Eduardo Ceja Mejia',
            'Edgar Ivan Lopez Martinez',
            'Jesus Alfredo Ayala Robles',
            'Montserrat Saucedo González',
            'Rocío del Carmen Bernal Zamora',
            'Yolanda Alicia Castillo De León',
            'Laura Elena Muñoz Pérez',
            'ROSARIO GUADALUPE DENIS FAJARDO',
            'Carlos Mijail Suárez Arredondo',
            'Yahaira Iracema Requena Castro',
            'Jesus Javier Solis Flores',
            'Érika Guadalupe Rodríguez De los Reyes',
            'Francisco Raymundo Sánchez Garza',
            'Mariana Herrera Pen',
            'María Teresa Medina Durón',
            'Jesús Flores Robles',
            'Raúl Garza Bulnes',
            'Fabiola Burciaga Córdova',
            'Gerardo Javier Muraira Calvillo',
            'Jair Sierra Flores',
            'Yadira Nereida Angel Correa',
            'Dante Iván Terrones Martínez',
            'Sindy Allazmin Rodriguez Miranda',
            'José Huerta Reyes',
            'Gabriel Martín Vargas Duarte',
            'Alfonso Javier Escudero Rendón',
            'Marco Antonio Ibarra Guzman',
            'Maria Cristina Ceballos Vela',
            'Fabiola Cruz Garrido',
            'Neyl Córdova Lara',
            'Rosa Miguel Fernández Nolasco',
            'Cesar Augusto Gil Rosales',
            'Isaías Santiago De La Rosa',
            'Roberto Herrera Torres',
            'Guadalupe Hidalgo Domínguez',
            'Joshue Eduardo Vergara Gámez',
            'Jaime David Alejo Cisneros Méndez',
            'Juan José Vázquez De la Garza',
            'Christopher Bello López Portillo',
            'Sergio Reynoso De Mendoza',
            'Ricardo Sánchez Stone',
            'Flor Lucía Morales Morales',
            'Elisa García Morales',
            'Sergio Luis Hernández Aceves',
            'Cesáreo González Bernal',
            'Marisa Jiménez Uríbe',
            'Horacio García Camarena',
            'Álvaro Bautista Vásquez',
            'Martín Ricardo Rodríguez Mora',
            'Juan Miguel Quiroz Gonzalez',
            'Salvador González Vargas',
            'J Felipe Rojas Nieto',
            'Mercedes Maria Teresa Gomez Mondragon',
            'KARLA ALEJANDRA LARA MARTINEZ',
            'Sergio Gonzalez Galaviz',
            'Jesús Ríos Gaona',
            'Ana Elena Martinez Soto',
            'Luis Javier Orozco Peña',
            'Carlos Augusto Soriano Beltran',
            'Gabriel Orozco Peña',
            'Arturo Samano Ruiz',
            'Antonio Padilla Bastida',
            'Sandra Lucrecia García Hernández',
            'Rolando de Jesús Rivera Sánchez',
            'Jose Jesus Villa Medina',
            'Jose Humberto Evaristo Avila Watanabe',
            'Fernando Garcia Martinez',
            'Sofía Pereira Corona',
            'Efrén Villegas Sánchez',
            'Martha Gutiérrez De Gress',
            'Roberto Arizmendi Villanueva',
            'José Luna Ruíz',
            'René Silva Alvarado',
            'Adrián Aarón Gutiérrez Villegas',
            'Marisol Flores Martínez',
            'Carlos Leyva Hernández',
            'Juan Roberto Enciso Espinosa',
            'Vicente Joaquín Lavielle Sotomayor',
            'Jesús Enrique Cuandón Escobar',
            'Jorge Luis Medina Luna',
            'Héctor David Vera García',
            'Michelle Jazmin Segundo Zavala',
            'Nora Alicia Aguilar Bernal',
            'David Oldak Skvirsky',
            'Paulo César Hidalgo Hernández',
            'Rogelio Vázquez Aguirre',
            'Monica Basaldua Tellez',
            'Graciela Zárate Covarrubias',
            'Raúl Francisco Trejo Velasco',
            'Claudia Berenice Rodríguez',
            'Elizabeth Ramírez Camacho',
            'Rodolfo Silva Ruíz',
            'Andres Vazquez De la Isla',
            'Blanca Medina González',
            'Jorge Cuauhtemoc Lomelí Cisneros',
            'Laura Monica Del Llano Feregrino',
            'Juan Alfonso Lopez De la Rosa',
            'Javier Navarro Morales',
            'Luz Adriana Nájera Loredo',
            'Juan Enrique Franco Hernandez',
            'Edgar Ulises San Vicente Santoscoy',
            'Dagoberto Delgado Franco',
            'Salvador Villalpando Carrión',
            'Adriana Leonor Salmoran',
            'Martha Cecília Razo Muñiz',
            'María Adela Ramírez Moreno',
            'Yahiel Osorio Alamillo',
            'Pedro Iván Barrera Martínez',
            'Ernesto Alejandro Diantes Sanchez',
            'José de Jesús Esquivel Barberena',
            'Patricia López Flores'
        ];

        $female_names = [
            'Adriana', 'María', 'Elizabeth', 'Ada', 'Alicia', 'Beatriz', 'Claudia', 'Marcela', 'Veronica', 'Sara', 'Gabriela', 'Carla',
            'Penélope', 'Juana', 'Diana', 'Eduardo', 'Sugeily', 'Laura', 'Isabel', 'Luisa', 'Victoria', 'Carmen', 'Sofía', 'Andrea', 
            'Lucía', 'Valeria', 'Paula', 'Daniela', 'Fernanda', 'Mariana', 'Camila', 'Renata', 'Alejandra', 'Ximena', 'Natalia', 
            'Estefanía', 'Gloria', 'Rosa', 'Clara', 'Esther', 'Elena', 'Silvia', 'Viviana', 'Raquel', 'Valentina', 'Marta', 
            'Virginia', 'Marina', 'Ana', 'Margarita', 'Antonia', 'Concepción', 'Nerea', 'Nuria', 'Paloma', 'Susana', 'Rocio', 
            'Rebeca', 'Raquel', 'Raúl', 'Lourdes', 'Isaura', 'Adela', 'Isabel', 'Josefina', 'Ana Maria', 'Joaquina', 'Lorena', 
            'Karina', 'Rosario', 'Belen', 'Almudena', 'Mariluz', 'Rosario', 'Aurora', 'Olga', 'Clotilde', 'Milagros', 'Manuela', 
            'Luciana', 'Valeria', 'Nadia', 'Xiomara', 'Estela', 'Silvina', 'Gisela', 'Yolanda', 'Elvira', 'Candelaria', 
            'Esperanza', 'Gabriela', 'Soledad', 'Graciela', 'Celeste', 'Beatriz', 'Alba', 'Teresa', 'Eulalia', 'Herminia', 
            'Olaya', 'Lourdes', 'Inés', 'Sara', 'Natividad', 'Celia', 'Ramona', 'Anunciación', 'Ofelia', 'Gertrudis', 
            'Apolonia', 'Dámasa', 'Teodora', 'Socorro', 'Encarnación', 'Luz', 'Araceli', 'Gaudalupe', 'Esperanza', 'Pilar', 
            'Consuelo', 'Angélica', 'Griselda', 'Mónica', 'Norma', 'Roxana', 'Yolanda', 'Lilia', 'Rosario', 'Zulema'
        ];

        $users = [];
        
        foreach ($names as $name) {
            $random_numbers = rand(01, 20);

            $name_parts = explode(' ', $name);
    
            if (count($name_parts) > 3) {
                $first_name = $name_parts[0] . ' '. $name_parts[1];
                $last_name = implode(' ', array_slice($name_parts, 2));
            } else {
                $first_name = $name_parts[0];
                $last_name = implode(' ', array_slice($name_parts, 1));
            }

           
       
            $gender = 'Dr.'; 


            foreach ($female_names as $female_name) {
                if (stripos($first_name, $female_name) !== false) {
                    $gender = 'Dra.'; 
                    break;
                }
            }

            $create_user = new User();
            $create_user->name =$first_name;
            $create_user->lastname =$last_name;
            $create_user->email =  strtolower(str_replace(' ', '.', $first_name . '.' . $last_name . $random_numbers . '@prueba.com'));
            $create_user->password = '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi';
            $create_user->save();

            $create_medical = new Medical();
            $create_medical->degree = $gender;
            $create_medical->phone = null;
            $create_medical->status = 1;
            $create_medical->user_id = $create_user->id ;
            $create_medical->save();

            DB::table('role_user')->insert([
                'user_id' => $create_user->id,
                'role_id' => 1,
                'user_type' => 'App\Models\User',
            ]);
        
        }

    }
}
